### ISSUE TITLE
Leaving "Track Artist" blank creates problems on Act Tech

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#100]
Ruby Riot created a mash-up of two songs for her act, so when she submitted the act she left the field _Track Artist_ blank but filled in the name of the track and the duration.

The act was accepted.

When she went to fill out her Act Tech Form, the form was pre-populated with info pulled from the application: Track name, Duration, and Track Artist (which was left blank).  Because she was there was an uploaded track, but no artist name, it prevented her from uploading the music and -- since she indicated she was uploading an audio file but hadn't -- submitting the rest of the act tech info failed.

Not a high priority fix.

**Comment by bethlakshmi** [comment]
So... what do you want to happen?  Should Track Artist be required?  On both forms?  
OR not required on both forms?
Or just have a better error message?

**Comment by burlexpo** [comment]
Currently it's not required on either form (at least, it doesn't say it's required on the Act Tech Form).  

How about something like, if it's blank on the Act Submission, the Act Tech Form automatically fills in "Not Provided"?

**Comment by bethlakshmi** [comment]
The reason it's not required on the Act Tech form, is that it's not required all by itself.  If you confirm no music, it's not required.  If you give music, we require the artist

If we don't feel that the artist is required, how about I change the logic so that if you provide a track and a title, you're OK.  And artist is optional always.

**Comment by burlexpo** [comment]
Sure.
