### ISSUE TITLE
Switching to PayPal, part 1

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#132]
This might be too big a problem to tackle in the time-frame we need it.  I don't trust BPT at the moment, and while I can use them to process PayPal transactions and have funds go directly to the GBE bank, I think we need to look at moving away from their services.

We have a PayPal account already and their API seems to have a solution which would fix the delay between the time a customer pays an application fee (for example) and the time they can use it.  https://developer.paypal.com/docs/integration/direct/webhooks/

The thing is, this would need to be implemented soon.  Like by June 15 at the latest, June 1 would be even better. This would **just** apply to applications (maybe vendor fees, since they're pretty simple too); we can look at implementing this as a solution for events later on.

**Comment by bethlakshmi** [comment]
Shall I start now?  Just cleared a tech debt ticket....

**Comment by bethlakshmi** [comment]
HOT DAMN!  Party on a Friday Night!  
Protoyping is complete - I got my branch working with [django-paypal ](https://django-paypal.readthedocs.io/en/stable/standard/ipn.html)and help from:

https://overiq.com/django-paypal-integration-with-django-paypal/

At this point, I'm convinced this is the easy way (and it wasn't so easy).  And that there really isn't a valid competitor for this library.

The basic features are:
- I have to seed the "Buy it Now" button with values that get configured by the code, that means that I can take choices about what values the user wants (like the value they want for an act bid, or the size of the vendor booth) - but I can't do it all on one page.
- I have a bunch of values I can pass to it:

  - business (required) | Email ID you used to create the PayPal business account.
  - amount (required) | Amount of the product.
  - item_name (required) | Name or description of the item.  It may be I can do more than one of these.
  - invoice (optional) | A number that uniquely identifies an invoice document - this, in particular - is forced to be unique by paypal.  We can't submit the same one twice.
  - custom (optional) | A custom value that can mean whatever we want
  - item_number (optional) | A custom value that can mean whatever we want
  - currency_code (optional) | The currency of the payment. By default, it is set to 'USD'.
  - quantity (optinal) | Quantity of the items. It must be positive.
  - notify_url (optional) | The URL at which PayPal sends the IPN.
  - return_url (optional) | The URL at which PayPal redirects the user after they make the payment.
  - cancel_return (optional) | The URL at which PayPal redirects the user if they cancel the payment.

It might be everything on [this list](https://developer.paypal.com/docs/paypal-payments-standard/integration-guide/Appx-websitestandard-htmlvariables/#individual-items-variables) - but some of this stuff and what it means is rather complicated to me, and would take some testing.

- The button takes the user to pay pal, let's them sign in, and pay.  When they choose to go back, they go to a URL I give it (the return_url) - which may or may not return them in a logged in state. 

- When Paypal gets the payment, it calls our application and tells us what was paid for.  The items are documented [here](https://developer.paypal.com/docs/ipn/integration-guide/IPNandPDTVariables/#ipn-transaction-types).  When it does, we note the payment.  I suspect that when it gets a success, it stops.  I will need to make sure to give it a failure if I can't process it.

- It has it's own database, but we'll want to have a way of noting what it means to us.

To Do:
- set this up with encryption, to keep the user from changing the button values on the page.
- design a flow for the user for the Act Fee and the Vendor Fee.  In each case, I'm picturing a workflow.   On the current make-bid page, they can specify the cost of what what they are paying for - Act fees would be an integer entry box that lets them set upward of the minimum amount in dollars.  Vendor fees would be a list of options (single table, double table, etc).  Either of these have customizeable values.  Then they "proceed to payment" as a button, and they get a confirmation page (made by us) of what they are paying for.  That page has the new Paypal button, and that button takes them to pay pal with the values they want to pay for. 
- figure out what the cancel & successful return pages do - I'd like to give an error/success/wait for it message of some sort
- correctly handle the signal for the payment.  My preference would be to make the item_name or invoice number connect to the bid, and submit the bid if the user payment is successful.  I really think for this flow, that's what they would expect.  When they pay, they expect shipment.
- Do something to track the date and source of payment.  So we can tell paypal from BPT.
- make the receiver email & sandbox Y/N configurable via a OS environment variable - so that I can separate out the test site from the production site and keep it private.  
- make a way to set up the minimum values and vendor bid items

Outside of scope:
- Discounts.  If you want to discount a vendor, or act, I'll need to do more work
- Comps - will be doable, but probably a hack.

**Comment by bethlakshmi** [comment]
I read through the Ticketing code, and I think it would be easy enough to add a few fields to what we've got.  Rationale - it preserves old logic, which may help with a few things, but also it helps if we ever use a ticketing service instead of a payment service... as the existing code is organized around events & tickets.  I suspect that while we may not use BPT for ticket sales this year, we may want something more ticketing-like for the actual even tickets.

Proposal:
- "**BPTEvent**" - can stay as is.  It has the link to what conference and whether the Event is actually an Act or Vendor fee.  Keep that.
- "**TicketItem**" - this is what the user actually buys.  It points to the BPT event, holds data for cost, title, "live" (meaning displayed on our pages), and other fields.  Multiple Ticket items can chain to 1 BPT event.  I recommend:
      - Add start/end date - if we are w/in the start/end date, the ticket item & price are an option for the bidder.  If there is NO start/end date - then the "Live" field decides if the item is shown or not.  This lets us do the "early bird" type stuff we did in BPT, w/out BPT.
      - Add a flag "is_minimum" - by default it's a fixed price, if it's a minimum, the user may choose (on our site) to donate MORE money, but the cost of the ticket is the minimum allowed.  (*)
- "**Transaction**" - the record of the purchase - points to the ticket, and the purchaser.  It already has amount paid, order date/time, payment source (will call it "Paypal").  Add:
      - Invoice ID - which we'll send thru paypal.
      - Bid Id - reference to the bid connected to payment.  Not a primary key link, but it represents the bid primary key.  I just don't want to formally connect the models.
- "**Purchaser**" - A ticketing construct that connects transaction and the Django user.  Can use as-is to keep a record of the user data we get from paypal.

When we send the request to paypal, we'll send - an item # with the ticket id, the custom field as the bid id, cost (of ticket selected), and an invoice that is ticket id + bid it + timestamp.

When we receive the record back fro paypal, we'll only store the successes.  We'll have all the fields mentioned form the sending, and also a bit more about the user and the purchase, which I'll save if I can make it work.

(*) = minimums really mess with the idea that there are multiple tickets.  Trying to give a UI that lets them pick from a list of fixed tickets OR a minimum is going to be a pain in the butt for me AND the user.  Instead, I propose that logic is:
 1 - get list of currently live tickets (start/end date or live flag=on)
 2 - if any of these is a minimum value - show the lowest minimum value as a single entry, ignore all others
 3 - if no minimum values - show a drop down list of all options for cost & payment.

When a user is setting this up in the ticketing info - I'll do what I can to warn them if they have hit a point where there is a minimum but more than one valid ticket.  I probably won't get every case, but I'll give it a shot.

**Comment by bethlakshmi** [comment]
@burlexpo - I've got something worth reviewing:

https://burlesque-expo-stage.us.aldryn.io 

Has updates that get me all the way to the user being able to pay.

Things to see:

**Create/Edit an Act**:
- if you've paid for an act fee that you haven't used, you'll see nothing different - you can submit the act immediately.  Nothing new there.
- if you have NOT paid, you'll see at the bottom that there's a box to input your donation for the act fee.  This is because I set the "Early Decision" ticket (which is the only one that is currently live) - as "is_minimum" - if the user enters < $20, they get an error.  Anything $20 or greater will work.
- when you press "Proceed to Payment" - you get a view of your shopping cart (so to speak) - which lists the ticket type you are purchasing, and the cost of each item, along with a total.
- when you press "Pay and Submit" - you go to paypal, which will prompt for login if you haven't yet.
     - THIS IS A SANDBOX - so you need to use my sandbox user account:  
           USER:  sb-hnddt1910816@personal.example.com
           PASSWORD: =t2&ggFb

That's as far as I've gotten - I will be able to redirect you back to GBE (did it in my prototype) and handle cancellations, and I don't have payment reporting yet.  I wanted to get you a look at look and feel of users getting through payment first.

**Create/Edit Vendor:**
- Same starting logic - if they already have a spare vendor fee, then they don't  get prompted to pay (no difference)
- if they haven't paid yet, they will get options at the bottom of their bid:
    - a drop down of required "main ticket" - they MUST pick one of these.
    - a checkbox list of add-ons - they can pick any or none of these.
- after proceed to payment - same cart view as act.  Works the same way, with the same sandbox.
- 

**Setup**:
- there is now a PayPal Settings item in the database (and on the /admin) - all it needs is the email address.  Right now it's using my sandbox account.  If you want to see how the merchant side looks, we can set up a sandbox for your account here:  https://developer.paypal.com/developer/accounts/
- under "Ticket Items" - there are now fields for start date, end date, is_minimum (ie, it's a donation minimum as for acts), and add-on (like renting chairs & tables). 


**Questions**:
- should I save the user's choices about donation/choice of options if they save draft.  That seems like the right thing to do... it's just more work...
- Are there any changes to labels or help text that you want?  The text at the top of big pages, and on the cart display page are editable in /admin - but the form labels/help text has to be coded by me.
- I can totally customize the button on the cart view - I made this button, it's an image.  If you don't like it, give me another image

Next steps - get the user-return links working, then process payments.

**Comment by burlexpo** [comment]
User experience:

- When I went to /act/create I had a weird, quick pop-up window which displayed for a second and then vanished.  It read "Info: Make Payment at Brown Paper Tickets
- Our records show that you have not paid your related fees. You can pay at Brown Paper Tickets by pressing the "Pay Fee" button below. Once the fee is paid, please return to this form and submit your draft. In the meantime, pressing either button will safe a draft of your application." but included all the HTML code.
- I tried submitting the act with a fee of $10.  Good news: it did catch the error and tell me the minimum is $20.00; Bad News: when I adjusted the fee to $20 and tried to re-submit the act, I got an error pop-up which reads "Error: You've aready created a draft or made a submission for this act. View or edit that act here: Mister Scratch TEST - GBE2020".  That seems like bad flow.
- After going "back" to the "original" and adjusting the amount, I clicked submit and was taken to https://burlesque-expo-stage.us.aldryn.io/act/edit/1371.  The text on that page has a link to pay at BPT.  We want that removed, right? (See image)

<img width="1440" alt="Screen Shot 2020-05-26 at 9 30 10 AM" src="https://user-images.githubusercontent.com/5369404/82906827-d130b480-9f33-11ea-885e-b67388950ad3.png">

- I was able to successfully "pay" using the sandbox. As noted, there's no auto-return to the GBE site.
- Manually returning to the GBE test site and looking at my personal page, I can see I have a paid application fee (see image)
- **NOTE** Also on /gbe under "Act Bids" there is a link to _Pay Fee_ for the Test act. Clicking that link takes me to BPT, so we'll need to clean those up as well.

<img width="1440" alt="Screen Shot 2020-05-26 at 9 35 45 AM" src="https://user-images.githubusercontent.com/5369404/82907604-d3dfd980-9f34-11ea-816b-09ca7d2879c2.png">

- Clicking "View/Edit this Act bid" successfully returns me to the Test act. However, I still have the error message saying I need to pay an Application fee (and also the quick HTML pop-up which goes away on its own)
- No option to submit act, only SAVE DRAFT and PROCEED TO PAYMENT

**Comment by bethlakshmi** [comment]
OK... taking these 1 by 1 - 

- When I went to /act/create I had a weird, quick pop-up window which displayed for a second and then vanished. It read "Info: Make Payment at Brown Paper Tickets...

This is true for any alert (the blue box on the page is an alert) - it happens because the alerts I use and the alerts the Django CMS uses are the same alert system.  You and I see it, and any one with django CMS see it.  No one else does.  If you make a second user and try it with that user (who doesn't have the right to anything in Django CMS) - you won't see anything.

I'm surprised you haven't noticed it before...

- I tried submitting the act with a fee of $10. Good news: it did catch the error and tell me the minimum is $20.00; Bad News: when I adjusted the fee to $20 and tried to re-submit the act, I got an error pop-up which reads "Error: You've aready created a draft or made a submission for this act. View or edit that act here: Mister Scratch TEST - GBE2020". That seems like bad flow.

Fair enough - will fix.

- After going "back" to the "original" and adjusting the amount, I clicked submit and was taken to https://burlesque-expo-stage.us.aldryn.io/act/edit/1371. The text on that page has a link to pay at BPT. We want that removed, right? (See image)

This one of the things I meant by the page text that we can customize with the Admin - for clarity, I changed many of the cases where that is true to a really obvious message that starts with "WE CAN CUSTOMIZE THIS IN THE ADMIN TOOL" - I didn't change them all, as there are some that don't really change with the new system.  It would help if you can have the text you want ready in a week or so when I'm able to finish this, I'll paste it into the admin tool after install.

- I was able to successfully "pay" using the sandbox. As noted, there's no auto-return to the GBE site.
Manually returning to the GBE test site and looking at my personal page, I can see I have a paid application fee (see image)

That's a red herring.   You have legacy payments from the existing system - I preserved that infrastructure, so we could obey payments in either system.  This should be equally true in the live system.  I guarantee, I'm not saving ANY payment details yet. :)

- NOTE Also on /gbe under "Act Bids" there is a link to Pay Fee for the Test act. Clicking that link takes me to BPT, so we'll need to clean those up as well.

Yep, it's on my to-do list.  Because the flow may need the user to pick some options before they pay... I suggest that I just remove it.

- Clicking "View/Edit this Act bid" successfully returns me to the Test act. However, I still have the error message saying I need to pay an Application fee (and also the quick HTML pop-up which goes away on its own) No option to submit act, only SAVE DRAFT and PROCEED TO PAYMENT

yes.   Because, as I said, I don't process the payment yet (ie, I don't have payment reporting yet).  

The 1 application fee you have, you used already on the act that is successfully submitted (Putting on the Ritz).  Per our logic, you need X application fees to submit X acts.  You have 1 application fees, you are trying to submit 2 acts.  You need to pay a second fee.  And you *did* - but I don't process your payment yet.

**Comment by bethlakshmi** [comment]
Sigh I made progress in my local environment....
- When you pay, after a few seconds, paypal contacts the site, and sends an update.  The site checks the update to make sure that the fee was properly paid.  If it was paid, the site marks it submitted, and also sends an email to bid reviewers (just as if the user had submitted it).

HOWEVER - I can't make this integration point work in our staging environment.  I'm stumped, so I'm contacting Divio.

Also....

TO DO:
- way better error handling.  I have none.  My plan is to send the *user* an email with any errors.
- QUESTION - should I email the user if they successfully submit?  Paypal does send them a payment notification... Shall I send an email as well?
- give the user a return link on their payment thread - I plan to return them to a "thank you... we're processing your payment" page that auto refreshes.
- testing the "process payment' stuff.

**Comment by bethlakshmi** [comment]
OK!  @burlexpo - the payment handling is set up on our staging site.  When you simulate a payment with the test user, it posts it to our site, which then registers the payment and submits the bid and you can see the purchase on your profile page.

The questions above still stand.

**Comment by bethlakshmi** [comment]
(wail of frustration)

I got the final step done this morning - a view screen that diagnoses whether the bid is submitted, needs to be submitted, needs to be paid for and responds to the user accordingly.   I got it linked into the paypal stuff, so the user would get redirected back and --- NOTHING WORKS.

I don't mean the new stuff doesn't work.  I mean that work from 2 weeks ago that hasn't changed at all doesn't work.  I submit a payment and it appears to work, but doesn't get noted in any of Django's systems.

I'm terrified that my library is too old and the paypal it's using fell out of main stream support.   I'm doing the following;

1 - escalating to Paypal developer support - waiting on answers (these guys take hours, I already did a go-round with generic customer support to no avail)

2 - looking (sadly) at https://github.com/paypal/Checkout-Python-SDK - which is referenced on the paypal site, and looks like a newer library.

If I do that, there may be a lot of rework, but I may be on something newer with better features.

**Comment by bethlakshmi** [comment]
OK.  The Tech support got back to me - they had a sandbox outage.  I just retested and things look fine - this was definitely on Paypal's end.

I'm worried - this is a major company, and I can't believe they had an outage they didn't diagnose for basically 24 hours.  This wouldn't be a hard test to automate.

But since I'm back in business, I'm planning to stay the course.

Work remaining:
- work out an error for when a duplicate payment is received
- make a auto-reload on the view bid page so that if a bid is awaiting payment, it can show the payment on refresh in case the site is a little faster than paypal.
- write tests for the view bid page

And then I'm DONE!  I think this is only a day or two of work.  Tuesday is pretty well screwed, but Wed. night post-hangout is an option.  So is Thurs between  things.  Or Sat. the latest.  Will aim to be done before Friday and do code review and install over the weekend.

@burlexpo  - what I'll need from you on install day - is a paypal account that I use for real.  And I'll set up a test bid for act and vendor where I pay you $1 or $.01 to make sure that the transactions work for real.

**Comment by bethlakshmi** [comment]
@burlexpo FULL THREAD IS READY FOR REVIEW!

I got the whole thing working - and it's up on the test server:
https://burlesque-expo-stage.us.aldryn.io

THIS IS A SANDBOX - so you need to use my sandbox user account:
USER: sb-hnddt1910816@personal.example.com
PASSWORD: =t2&ggFb

Please review and give last comments before Saturday.  I have final full coverage testing, but should be setting up a self-review NLT tomorrow night.  I'll then review, close and deploy on Sat/Sun.
