### ISSUE TITLE
Weird "Main Ticket" display on application

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#217]
Down at the bottom of the application form, there is an extraneous field which says "Main Ticket" with a pulldown menu (which doesn't go anywhere).  Fortunately, it's only confused one person thus far.
<img width="1440" alt="Screen Shot 2021-06-15 at 5 40 53 PM" src="https://user-images.githubusercontent.com/5369404/122127482-38e8c480-ce01-11eb-8dec-8e769e7449d8.png">

**Comment by bethlakshmi** [comment]
OK, this happens some of the time (when you create a new persona and then get directed here).  But not others (create a new act when you have a persona).

Looking into it.

**Comment by bethlakshmi** [comment]
Curioser and curioser --- not quite that.  My test site has it.  I can't reproduce on the live site.  Did you change any ticket related info there recently?  For the record - I haven't pushed anything ticket related to the live site recently... but this looks like the finger prints of my work from incorporating PayPal 6 months ago. 

Are you able to trigger it?  Or was this from the user?  Any details you can give me might help...

**Comment by bethlakshmi** [comment]
FOUND IT!

![Screen Shot 2021-06-15 at 5 58 52 PM](https://user-images.githubusercontent.com/4542707/122128981-66cf0880-ce03-11eb-9ba8-55b74dd62b9b.png)

TODAY our main ticket expired.  You had wanted to set the Donation ticket to last until 6/15 - today is 6/15 - there is no other ticket available in GBE to let people pay to submit an act...  I set it to 6/16 to give some breathing room - but what do you want to do for act submissions?

**Comment by burlexpo** [comment]
We need to be able to set application tokens for special guests and such. I can submit applications by hand through admin but I always feel like that screws things up. 
--
Team BurlExo
Burlesque-Expo.com
#BurlExpo

**Comment by bethlakshmi** [comment]
OK, so this ticket needs to morph into 2 things (per our conversation a few days ago):
1 - a way for Scratch to comp people - my recommendation is that I make a thread that lets Scratch insert the record of a payment into the special user's account.  That saves the back and forth of coupon codes.  Then the performer can just submit their act.  That's what we did manually for Guilted Lily last week.

2 - set up a way to set availability for bid application - per bid type - and hide GBE-code-controlled buttons/links/etc when the bid application period is not started or already done.  If the user has purchased (or been comped) an application fee, however, the buttons and forms are still available to that user, even if the bid availability period is over.  That handles the case of special people who have different rules (acts and vendors only -- since classes & costumes don't have fees, they are over when they are over)

QUESTION:  Should the special after-deadline application option be limited only to special people that Scratch has comp'ed?  To do that, I could add a flag to the comp process, so that you say "yes, this is a special comp, and the person can use the form after the deadline" (a checkbox), and then ONLY if the user has a special comp can they see the buttons and forms and all.

OR -- should anyone who purchased a fee for that bid type be able to use it after the deadline?  With the current system, the action of paying for your fee submits your bid.  So this case is extremely unlikely.  But with the old BPT way of doing it - if the person bought on BPT and forgot to got back in 15 minutes and submit their bid, then they had a paid draft and they'd be able to submit, even after the deadline.  Does that matter?

NOT putting in a special flag is easier than putting in the flag... but it's not that hard.  So if it helps, glad to do it.

**Comment by burlexpo** [comment]
Here's what I need:

1) At anytime (before, during, and after the general open application period) I need some way of giving someone a free application fee.  Ideally, this is me giving them an application "ticket" and not me waiting until they are done creating their application and then doing something by hand.

2) Some way of allowing the general public to apply **only** during the open application period.  Even if that have paid an application during the application period, if they don't use it by the time it ends, that's too bad on them.  Yes, the reality is if someone contacted me today and said "I paid my fee before applications closed  but didn't submit my application", I would still let them apply, but I want them to realize they screwed up.

3) Some way of special people applying before, during, and after the open application period.  I don't care if that means I flag a person as special or I flag an application as special or there is some application page that is hidden and password protected and I tell them the password.

**Comment by bethlakshmi** [comment]
How about - when you comp a special person with a ticket purchase that you created, the comp itself is special.  The comp has a flag on it that grants the user holding this comp the ability to submit after the deadline.

Then - if you have the case in (2) where someone contacts you and begs, you can let them apply with the same mechanism?  you mark their payment as special, and they can do a last edit and submit their act?  Same mechanism for how the user is allowed to do something special, but a slightly different flow for what you do as in this case you find a user with a draft act and a paid submission on a regular ticket and you mark that payment, instead of creating a new one.

**Comment by bethlakshmi** [comment]
The comp ticket flow is up on test now.  I realized I still need to write tests for it, so putting this on hold in favor of the auto-email on tech info.

**Comment by bethlakshmi** [comment]
Pushed comp workflow to master and am currently deploying
