### ISSUE TITLE
Stage Manager Abilities

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#218]
Stage Managers are currently attached to a single show.  I'm fine with that.  Ideally, a stage manager could only effect/find out info/etc about their show, but if SM's have the ability to effect every show, I'm fine with that too.  We'll just tell them not to mess with other people's shows.

SMs should be able to 

1. - Mail to the performers in their show (Essential)
2. - Research an email address/contact info for _any_ performer (Useful)
3. - **Remove** a performer from their show (but _not_ add one) (Useful)
4. - See which performers are signed up for which rehearsal slots (Essential)
5. - Get a report which shows which performers aren't signed up for a rehearsal slot (Optional)
6. - Add a performer to a rehearsal slot (Useful)
7. - Approve volunteers for their show who are in the "Stage Crew" area (Essential)
8. - See which performers have submitted their music (Useful)
9. - Upload a music file on behalf of a performer (Useful)
10. - See which performers have submitted their tech info (Essential)
11. - Edit a performer's tech info (Useful)
12. - View the order of acts within their show (Essential)
13. - Change the order of acts within their show (Useful)

**Comment by bethlakshmi** [comment]
I numbered your bullets for sanity.  I'm going to be mentioning them

**Clearcut stuff with estimates**
- giving a role a scope of authority based on their assignment to an event (ie, the stage manager can do stuff with settings/data for their show, but not for other shows, or special events, or other stuff) - is more than we've had before, but it's totally doable (medium effort).  That would make it pretty easy to build up:
       - email by role only for the shows the SM is involved with (item 1))
       - view act tech info only for the SM's show, which gives the what performer <-> what rehearsal slot info (item 4, 5, 8, 10, 12)
       - schedule acts for their show - (item 13)

**Questions on harder things:**
- item 3 - the only performer removal we have right now is on the act bid pages - a coordinator can accept OR reject acts - and that's how we remove the act from the system.  That seems like a weird privege to give stage managers, as it means they can accept/reject performers for all shows, and it's pretty hard to limit that.  Is this the flow you meant?  Or are you seeing the privilege somewhere else?
- item 6, 9, 11 - the way I'd implement this is to let the SM submit the user's act tech info for them.  Both these things are in that form.  That would be in the "medium work" area above.  The impact, though, is that after the SM does that, the user alert saying that the user needs to fill in their act tech info goes away and the act tech report no longer shows the tech form as filled out.  Also - I don't think the system will send the perform any email or anything.  That's all probably fine if our use case is that that user is standing next to the SM at the conference and the SM is doing tech stuff for them and keeping them in the loop.
- item 7 (essential) - would it be OK if the SM could approve ALL volunteers for their event that need approval?  That would make this a lot easier.  Having there be a special mapping between which roles/volunteer types the SM can approve and which others they can't adds yet another type of complexity to the code.   My proposal puts item 7 into the "medium work" pile above.


**Checking on what you mean:**
- item 2 - Not sure what feature you mean here.  I can think of three things:  Special-> Manage Users has all the user contact info, but no info on who is a performer.  Email by Bid would get all act proposers and all accepted act proposers (which would be all performers) for every conference.  Email by Role could get all performers for all shows.  The last two give email, but not other contact info.  The first gives contact info, but not other stuff.  

Reading all this - it sounds like the most urgent area is really on the stage management side - which is all around per-event access to show/act/performer data and decision making.  I think what I'm gonna do here, is build out a type of flexibility for that, specifically, and then in a separate ticket, get the other roles to follow that new pattern.  It's time, IMO, for the system to NOT hardcode privileges (all these items) to roles (ie, SM), it should be something that can be turned on/off from the admin, the way the django default stuff is (that's what you see in the groups page).  I'll do that here, and then catch up other role/privs later.

**Comment by bethlakshmi** [comment]
Writing this down because I've been thinking it through and don't want to loose the thoughts.  This is too big to attack 2 mo before the expo.   But here's what we really want:

- The scope of a user's authority is based on what event they've been assigned a role in.
- There's a connection of User -> Role -> Event and User -> Role -> Privileges where Privileges are actually pretty reasonable things like "view act tech", "edit act tech", "approve volunteers", "reject volunteers", "schedule acts" - where the implication is "for the show they have a role in.   Ideally, the admin can both set up a new role, and assign it low level privileges.  Neither option is available in GBE right now.
- For Staff Areas, because that's not an Event - it works similar, but different - I'd want to handle it separately, but with an eye to what I do here.  It would be hard to have different staff area leads have different privileges - "Staff Area Lead" would basically be the peer of "Stage Manager"
- A certain amount of complexity comes in where the volunteer event staffing is a sub-event to the show - so the User -> Role (stage manager) -> Parent Event (with permission) -> sub event (volunteer event) -> volunteer to event relationship is actually what's getting manipulated.
- Django natively has the relationship of User -> Group -> Permission (per model class).  There are a bunch of authorization packages that extend Django to let the user put in logic that is per model object (more granular than class), and the Django framework itself can also be pretty easily extended for that.  But nothing I can find tackles being more granular about the user's way of obtaining permission (User -> group) in a flexible way.

I did a bunch of design tradeoffs and my best best (of the moment) is:

- use native Django to extend Permissions on objects - some of these custom permissions are explicitly "per event" - and will be labeled as such.
- put roles into the scheduler database - connect a role to a group explicitly - let that connection be 1:1 - roles are what show up in all the event scheduling stuff.  This includes roles for things we don't normally think of - like "rejected" volunteers, "interested" people, etc.  This includes making the class Worker have an optional Foreign Key relationship to Roles.  That's there now, but it's an enumerated choice.
- Pull out the other enumerated controls for roles into the new Role entry in the database.
- There's a bunch of work here in terms of getting the forms setup, view changes, and the IDD to the scheduler.

Putting all this on hold until after the Expo.  Will write what I actually do in the next comment - we'll do something that has no per-event access, but hoepfully most of what Scratch needs.

**Comment by bethlakshmi** [comment]
What I'm actually doing:
- there is no role (at all!) for Stage Manager - I'm adding that to the list of event roles that can be scheduled for a show, and then adding it as a privileged role. The Stage Manager is only privileged as long as the conference for which they are a stage manager is in the present/future - if the conference is "completed" their role is no longer valid.
- Set up Special menu access for it
- Add it to the email by role feature - restricting it's access to Shows, and roles "Performer", "Volunteer", "Staff Lead", "Stage Manager", "Technical Director", "Producer" - that at least limits their abilities, but it does NOT limit it to the show they manage - they can get to any show. Of note - Staff lead already has permission.  See the evolving notes on special access [here](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/wiki/Special-Access)
- Give Access to Act Tech Info Report - that shows them items 2, 4, 5, 8, 10, 12 but not limited to the show they manage.  It is, however, on a per-show basis.  
- Also give access to the act tech info detail - I can't think of any reason they shouldn't see act tech details, if they can see the summary.
- Give access to schedule -> acts - which lets them do item 13
- Give access to Reports -> Volunteer Staffing Reports - that gives them all staff area and all show performers and volunteers - so a tad bit more email information than they had (staff area volunteer emails) but worth it for the added insight, IMO.
- add to the volunteer approval page - so they can approve their volunteers, that means they can approve EVERYTHING - so if they approve a reg desk offer - that is allowed.

That covers all the Essential (although without limiting scope much).  And many of the Useful (not all of them), and also the 1 optional.  

Gonna stop there and test, await new priority and fix that bug I just filed.

**Comment by bethlakshmi** [comment]
@burlexpo - I just deployed a bare min approach on test server.  And I made a sample stage manager account there:

username = betty_stage_manager
password = test

She's been assigned to Sunday Showcase as a Stage Manager (a new option in event scheduling).  That's how she got all her superpowers.

I'd love it if you can log in and see if it's good enough?  Take a look through the special menu options, see if that's close enough to what you need.  Also do a dry run of email to roles - notice that there are some limits on what she can see, although not *quite* as limited as you'd like, but compared to your super duper admin status, a lot less.

**Comment by burlexpo** [comment]
I took a look.

On the _Special_ Menu

-     _Contact > Roles By Mail:_ It looks like as Betty the SM I can mail to every conference and every role, but only to shows? Is that right?
-     _Report > Act Tech Report:_ It looks like I have access to all tech reports ever.  I can select any conference past or present and I can select any show. 
-     _Report > Volunteer Staffing Report:_ It looks like I can see all of the Volunteers for any area.  I wanted to see if I can remove someone who was signed up as a volunteer, so I clicked on "Edit" next to the Bordello Stage Kitten (Guilted Lilluy is assigned).  When I go click edit, I get a 403 error.
-     _Review > Volunteers:_ Defaults to the current conference.  It's hard for me to know what I'm looking at there.  Are these volunteers who need approval? What about volunteers that have already been assigned?
-     _Schedule > Acts:_ It looks like I can set the order for any show and it defaults to the Bordello.

---------------------------

There doesn't seem to be anything on the **dashboard** which indicates that Betty-the-SM is stage manager for a show.  On your schedule it lists the Sunday Showcase, but not what your role is.

What I'm hoping to do is to make this dirt simple for people, because people are dumb.  The "Special" menu is kind of confusing.  It's not super-intuitive of where you would go to do a particular thing or find particular information -- because, like with so many other things on the site, we're kind of building on things that weren't built by people who valued simplicity.

Is it possible to create a menu item under the Special menu that would take someone assigned the SM role to an "SM page", which has a couple of task-related buttons and maybe some default reports on it? That might streamline some things.

For example, instead of having _Special>Contact>Roles By Mail_ there's a button on their Stage Manager dashboard which says "Mail Performers" and when they click it, it takes them to the same result they would see if they had gone to Roles By Mail and selected the Current Conference & Performer, clicked "Filter", and then selected whichever show they are assigned to.  Similarly, a "Mail Volunteers" button which, when clicked, takes them to the same result they would see if they had gone to Roles By Mail and selected the Current Conference & Volunteer, clicked "Filter", and then selected whichever show they are assigned to.

The Special>SM page could also have the pre-generated reports that an individual SM might be interested in.

Even if we created Special>SM>The Main Event and when a user was assigned the SM Role for any show they got access to the SM screens for all 4 shows, it would be a way to gather a bunch of information in one place, rather than having to go to a bunch of different menu items/screens.

**Comment by bethlakshmi** [comment]
OK answers:

- _Contact > Roles By Mail & Report > Act Tech Report_ - yes, it's all conferences, all shows.
- _Report > Volunteer Staffing Report_ - huh, if i keep this report available to SM's, that's a good bug - the Edit button gets you to schedule editing - which is a lot more power than you wanted to give SMs.
- _Review > Volunteers_ - yes, this is only volunteers who need approval.  OR that were rejected, which we might want to approve if the approved volunteer falls through.  The volunteers who volunteered for events that DIDN'T need approval are in the volunteer staffing report, but not shown here.  This wasn't designed to be a report of every volunteer ever, my impression when we reworked volunteering is that you wouldn't want to see that.
- _Schedule > Acts_ - yes, it defaults to something like the first show in alphabetical order.

--------------------------

Yes - on the dashboard for the schedule, we don't list ANY role - there's not a lot of room there.  If you want me to change that, I'd change it for all roles. 

_"because, like with so many other things on the site, we're kind of building on things that weren't built by people who valued simplicity."_

I know you didn't mean this to be hurtful - but it was.  Please don't assert stuff like this.  At this point, I have written and/or re-written 100% of these pages.  You really don't know what what is my head when I was working on this stuff.  Point of fact - I WAS trying to make it simple - for YOU.  And you haver a number of different needs that the SMs don't have - like being able to mail people from prior conferences to recruit them.

OK... so -- from the initial privilege list - I didn't realize you wanted to have a one-stop shop dashboard type thing to do most of this (or be a jumping off point to it).  I can do that, but it'll definitely be more like two weeks, and less like a day or two.

Any ideas on what would be a good basic layout for a report for this?  Act Tech Info summary page for the show + the volunteer list for the show (from the staffing report)?

And then a bunch of buttons like "Mail Volunteers", "Mail performers" etc?

Would it also couple up with the act order pages so they can view the tech stuff and reorder at the same time?

**Comment by bethlakshmi** [comment]
@burlexpo - I put another version up on the test server (see link in this thread) - same user, same password.

This is definitely a work in progress.... stuff to see:
- home page has the button we talked about - this user is Stage Manager for this show - so they get a button to manage that show.
- button takes you to a 2 panel view - both act and volunteer panels have the data I intend.  The Act Tech Info is editable (includes booking rehearsals) and the act can also be removed.  All buttons should work.

TO DO:
- make 2-3 buttons for "mail performers", "mail volunteers" and "mail everyone involved in show"
- Let the volunteers be approvable (? and removeable??) - I think I can put buttons on the volunteer table and let stage manager approve any pending volunteers.
- make the acts scheduleable in the act table.  Turn the "order" column into an integer select box and then put a button for "set act order" on there.
- maybe - See what I can do to make +'s into triangle arrows.  (will do tickets, too, if I figure it out) 

Then if I have all that working, I will remove the special menu links, since they don't really need them.

**Questions**:
- how does this look?
- if I give you a way to navigate to this for each show, can I remove the schedule-acts old page (Special -> Schedule -> Acts)?  And the "Act Tech Info" report (Special -> Schedule -> Act Tech Info)?
- Also - can I remove the Special -> Report -> Volunteer Staffing Reports - specifically for Shows.  I think this is a way better view for everyone, and I am finding some annoying bugs in that format that I'd rather not fix.

**Comment by bethlakshmi** [comment]
@burlexpo  **Question:  Should stage managers be able to :**
- pull volunteers from "wait listed" to "approved" (code would auto-send an email)?  
- reject volunteers?  if so, does the volunteer have to be in a pending state?  or might they also be already approved/signed up in a no approval needed role.  "Reject" means the volunteer gets an email notification, and they can't resignup for that slot.

**I'm really, really close to done, so an answer in a day or two would be super helpful.**

Also please answer previous questions in previous comment on this thread.  There is a working model of everything EXCEPT volunteer approval up on the test site.

**Comment by burlexpo** [comment]
Should stage managers be able to :

- pull volunteers from "wait listed" to "approved" (code would auto-send an email)?
Yes
- reject volunteers? if so, does the volunteer have to be in a pending state? or might they also be already approved/signed up in a no approval needed role. "Reject" means the volunteer gets an email notification, and they can't re-sign-up for that slot.
Yes, they can reject a volunteer -- whether in a pending state or removing an assigned volunteer.  We want SM's to be able to yank people who have sent them an email saying "I'm not coming" without having to tell me.

**Comment by burlexpo** [comment]
More Answers:

_how does this look?_ Really good.  Can we make the buttons on the Dashboard look more "button-y"? Add a drop shadow or some slight dimensionality or make them pills rather than rounded rectangles? Or all 3?

_if I give you a way to navigate to this for each show, can I remove the schedule-acts old page (Special -> Schedule -> Acts)? And the "Act Tech Info" report (Special -> Schedule -> Act Tech Info)?_
Yes, but it's not just me.  Audio Lead and Lighting Lead need to be able to see the tech info pages.

_Can I remove the Special -> Report -> Volunteer Staffing Reports - specifically for Shows._ 
Yes, that's fine.  I think this is better too.

**Comment by burlexpo** [comment]
I tested all of the functions on the "Manage Show" page --

- Can view video
- Can edit tech info
- Can view tech info/intro/etc
- Can remove an act from a show

I didn't test the three mail buttons because doing stuff on Test won't email people -- right?

**Comment by bethlakshmi** [comment]
Right! On the test server  - email gets sent to you and I and no one else,
regardless of who it was actually sent to on the test server.  So you'll
get the email that would be sent to ***@***.*** - so you
can see if you like it.


Question - on the Audio & Lighting leads - do they need view access only or
edit access too?  if yes to both volunteers and act tech?  Should I
segregate Staff lead access so that some leads have access to show info and
others don't?   (like, head of registration doesn't need this....)

Also - in terms of navigation for people who have all-event privileges
(like you and I), would it work for you to have access to this dashboard on
either/both the Calendar, and the Manage -> Events page when the event is a
Show?  I'm figuring neither of us want a ton of buttons on our landing
pages...


- more button-y buttons - do any of these work better for you?
https://bootstrapbay.com/blog/bootstrap-button-styles/
    Am I making this a unique thing, or trying to be more like this with
all buttons everywhere?

- I also realize that to totally remove the schedule-acts feature, you
needed to be able to change what show an act is in - is that a separate
privilege (can stage managers do it?) if so, shall I just use Act
Coordinator for that?  (Producer is also an option).  I'm working on a
sweet little button & popover that will let you do that on an act by act
basis.  If we want to not destroy the order of acts, though, it will do the
act booking into new shows on a separate tab in the browser.  That's a
little crusty, but this isn't a single page app, and I am not running on
APIs that would let me be more elegant.

I worry about two flaws in the design on this page:
- you have to close acts to open volunteers.  Is that annoying?
- if you do any sort of button click, it will flush your order of acts -
that's a really hard thing to fix.  Even when it seems to stay on the page
(like when you approve a volunteer), you are actually reloading the page
and returning to any previously saved state.  I worry that this is just not
what normal people expect from their web pages anymore - we all expect
things to act like Facebook, where you can have 2 messenger thread, a long
winded post, and an open comment on a friend's post, and these things don't
interfere with each other.

-Betty

**Comment by burlexpo** [comment]
_Do Audio/Lighting Leads need view access only or edit access too?  if yes to both volunteers and act tech?_ 
Edit access to both.  I want the leads to manage their own volunteers.  I want them to be able to have a conversation with a performer during rehearsal and when they realize what the performer has asked for online is not what the performer actually wants, for the tech lead to be able to edit the form so that they have accurate information to refer to during the show.

_Should I segregate Staff lead access so that some leads have access to show info and others don't?_
Yes, as you say, some staff leads don't need this.

_Would it work for for people who have all-event privileges to have access to these functions on either/both the Calendar, and the Manage -> Events page when the event is a Show?_
Yes, that's fine.  Keeps the personal dashboard from getting cluttered

_ Buttons: https://bootstrapbay.com/blog/bootstrap-button-styles/ Am I making this a unique thing, or trying to be more like this with all buttons everywhere?_
I'd like all buttons everywhere to be both "Round" and "Raised".

_ I also realize that to totally remove the schedule-acts feature, you needed to be able to change what show an act is in - is that a separate privilege (can stage managers do it?) if so, shall I just use Act Coordinator for that?  (Producer is also an option)_
No, stage managers can't move someone to a new show.  They can remove performers from a show, but they can't add them to a show -- right? And, ideally, a stage manager can only impact the show they are assigned to.  I think "Producers" can add acts to the shows they are producing.

_You have to close acts to open volunteers.  Is that annoying?_
I don't think so.  It's really two different headspaces.

_if you do any sort of button click, it will flush your order of acts; that's a really hard thing to fix._
That's kind of frustrating.  At the very least it'd be nice to have (similar to Facebook), a warning that says "You haven't finished doing the thing you were doing.  Are you sure you want to do a different thing?".

**Comment by bethlakshmi** [comment]
Updated the test site.
- new buttons - please take a look - I'm worried that there's a lot going on on the light pink buttons, as there is hover/focus color changes too.  Let me know if i should tone it down.  I also did the dark red, pink and cancel buttons, but NOT the buttons in tables - because I'm worried that making those look this way will be really weird.
- See the new "Show" button in the acts area - the test users has this because she is also an Act Coordinator (or producer) - others won't get it.
- also updated Volunteer approval/reject buttons to be what I think you want.

**Comment by bethlakshmi** [comment]
Another update - navigation for Staff Leads to have a button on their landing page is in.
And for the likes of you and I - there is a button on the Calendar and on the Special -> Schedule -> Events page for any show (no button if not a show).

I *think* that's the end of the requirements. 

The one thing I did not do is a popup warning to a user who is working on scheduling acts and who then presses a link.  I know this is doable with Javascript, but it's a bit more nuanced than I've done in a long time, and to be actually effective, we need:
- the popup happens anytime there's a risk of loosing act schedule details from clicking on a button - that's a LOT of buttons in this form!
- the popup should only come up when the act order fields have been changed (ie, when there is something to loose).  If the popup comes up all the time, regardless of actually loosing changes, the user will very quickly become annoyed and then numb to it and they'll just click through it.  Facebook's popups are effective, because they only come up when you are into something that you may not want to loose.

I have some inklings on how to do it... but I'd rather do this on a separate ticket.  It's not a lot of code, but it's a lot of fussy testing.

**Comment by burlexpo** [comment]
I have some inklings on how to do it... but I'd rather do this on a separate ticket. It's not a lot of code, but it's a lot of fussy testing.

Sounds good to me.

**Comment by bethlakshmi** [comment]
Just merged and pushed to live site.
