### ISSUE TITLE
Make 3D buttons

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#244]
https://designmodo.com/3d-css3-button/

**Comment by bethlakshmi** [comment]
OK, just we're in complete agreement - I will do ALL the stuff in this site, and thus make a button that looks and acts like this:

https://designmodo.com/demo/3dbutton/

Including the perspective of it being a trapezoid, and having a sort of tilting quality when pressed.

And... I'll do it to all of our buttons?  As in:

- all the buttons at the bottom of every form
- ? all the buttons in all the tables ? - I'm worried about this, as there's not a lot of real estate on those.. also they are a group (smooshed side by side) and the trapezoidal look may be very odd with these.  I recommend I hold off on those (none of them are normal user places, they all require privileges).
- the buttons at the top of the tables (used to select columns)
- random buttons everywhere - there's a lot of actions in button form - like Volunteer on the home page, and the various propose act/class/etc buttons.  And filter buttons on administrative pages, etc.

And... I'll do my best guess at gradienting colors that are currently in place in the live site - including green (primary), pink (secondary), light and medium gray.

---------

Suggestion - I suggest I also update the style management area to make a button management area, so that you can fool with the colors in something less awful than the template color list.

Let me know quickly if you DON'T want me to:
- do all parts of this demo
- skip the table buttons
- spend a little extra time making a manageable button color area in theme management.

**Comment by burlexpo** [comment]
I don't know what elements are easy to separate out and what makes things harder for you.
I don't like the trapezoid, so I'm happy to lose it.
I do like a "depression" quality when clicked
I'm fine holding off on the buttons in places that require privileges to get to.
I like the suggestion of updating the style management to make a button manager

**Comment by bethlakshmi** [comment]
Sweet!  I think I got everything but the trapezoids, see picture.  The trapezoid is both experimental and driving me nuts.

![Screen Shot 2021-07-26 at 11 00 54 AM](https://user-images.githubusercontent.com/4542707/127011608-b8e7c12c-6a32-4592-bfa5-98579a7e461f.png)

And I got it to depress (hard to do a screen shot of that).

Definitely we want a button manager.  The styling on this is intense, but I think we also need humans to decide on:
- color of button
- color of font
- shading to make font look a little depressed (has to play well w color or font looks fuzzy, and not 3Dish)
- color the *side* of the button (you want it a little darker but in the same color tone)
- border of button

Other stuff - like the shading - can be done with overlay transparency colors.  So I'm thinking a table of buttons - each column is a button, and then under it is the relevant settings.

**Comment by burlexpo** [comment]
Those look great! I will admit that maybe we can get someone else in to consult on the color choices.

**Comment by bethlakshmi** [comment]
That would be fantastic.  The green color looks odd to me, and I don't think that the most prominent function on a page should always be green - the green of the check mark (for example) and the green of the button are not the same thing.  But this is a blend of color theory and user experience design that are not my forte.  I know how to stay sane-ish/safe-ish but not how to make it really look great.

**Comment by bethlakshmi** [comment]
OK, probing on my edits a bit further and I'm in a conundrum on this - we have some "secondary" color buttons that are connected to various spiffy 3rd party input functions - do I made these 3D?  Or leave them flat?  

Example - this button is for the calendar popup, you press it and the calendar appears:

![Screen Shot 2021-07-26 at 2 25 42 PM](https://user-images.githubusercontent.com/4542707/127039588-43f7d5a3-406e-4fc7-a82b-e0481361d825.png)

I fooled with this button a bit already when I did the new theme editing stuff, I made sure it looked and acted like our "secondary" buttons since that's effectively what it is - it's a supporting thing to the main operation of the page.  Because it, and the text box next to it are made by the widget code, I can do stuff to it, but I have a bit less control.  For example, if I change this text box, I risk changing ALL our text boxes, because there's nothing particularly unique about it for me to reference....

I can give that calendar button 3D qualities:

![Screen Shot 2021-07-26 at 2 19 12 PM](https://user-images.githubusercontent.com/4542707/127038914-c16d32ec-5c33-47f9-94b0-f6ff1f83954b.png)

If I do what I did above, the item has a nice 3D affect, but seems weirdly mis-aligned with the text box.

I can squash that down a bit - and make it bottom align with the bottom of the input field:

![Screen Shot 2021-07-26 at 2 24 15 PM](https://user-images.githubusercontent.com/4542707/127039438-c16bce74-269a-40b5-8e4e-a3dfa6271b40.png)

But then it looks hinky next to the "change dates" button...

I suspect the best outcome is to move the change dates button to the next line.  Then they aren't on the same row and they won't look so messed up.

But... this is just one case - I'll need to go through and check up on stuff.

Also - I think I'd rather get into File Edit buttons on a differerent ticket:

![Screen Shot 2021-07-26 at 2 33 59 PM](https://user-images.githubusercontent.com/4542707/127040701-56bb0532-655e-4aae-b867-634c994731c3.png)

These guys are made by Django when it draws out form stuff for me.  I can make that give me a class, and then modify that class...  but that gets bigger still...  if you want that, please write a ticket for it.  We would also want to decide... I think this would be a "secondary" button...

**Comment by bethlakshmi** [comment]
done and deployed.

You can see the new button editor here:

https://burlesque-expo.com/themes/style_edit/1
