### ISSUE TITLE
Teacher/Persona Bugs

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#248]
I suspect these are all related:

1) If I go to https://burlesque-expo.com/bios/teachers/ and count the number of teachers, I get 17.

2) If I go to https://burlesque-expo.com/email/mail_to_roles and select
- Conference GBE2021
- Roles: Teacher, Moderator, Panelist
I get 12 email addresses.  I should get 17.

3) If I go to https://burlesque-expo.com/email/mail_to_bidders and select
- Conference GBE2021
- Bid Type: Class
- State: Accepted
I get 16 emails addresses.  Which is OK, because two of the 17 teachers are me.

4) If I go to https://burlesque-expo.com/bios/teachers/ both of my persona are teaching classes (Mr. Scratch and Scratch)
**Scratch** is listed as 
_Teacher_ - Who's Who in Classic Burlesque
_Panelist_ - Panel: The Body of Work: Longevity in Burlesque

**Mr. Scratch** is listed as 
_Teacher_ - BDSM* 101 (Burlesque Dancer Social Media)

5) When I go to my dashboard there is no way for me to change which persona/bio is associated with what.  I suspect I submitted one class before we had multiple persona, and one afterwards.  And that Red Velvet assigned me to the Panel and she just picked one of my persona.  

**Action Items**
- Figure out why some teachers aren't showing up.  The ones that don't appear are: Alice Rainka, Anabel G., Angie Richer, Lulu LaFemme
- On the Dashboard, change the label in the middle column that reads "Performer Items" to "Personas"
- Can we add radio button at the top of each Persona page (I.e., https://burlesque-expo.com/persona/284/1/) that says "Use this persona for (  ) Acts     (   ) Classes    (   ) All Activity".  It should be a required button with no preselected choice.  It should check for conflicts and simply not allow someone to select a choice that is already in use.  The user should be able to come back and edit the choice.
- Can we add a "Delete" button to the button of each Edit Persona page? I know I have some I would love to delete (Testy McTestface, for example)

**Comment by bethlakshmi** [comment]
OK, so central thing in the system:

- bidding does not give a user a role.  A user gets a role by - being explicitly assigned a role in the admin, being assigned a role in an event, being assigned as a staff lead to a staff area. So...
     - a person who proposes a class is a bidder.
     - a person whose class has been been accepted is a bidder with an accepted class.
     - a person whose class has been scheduled - is NOW a teacher.
     - if their class is deleted from the schedule, and/or their scheduled class is assigned a different teacher - they are no longer a teacher (unless they have some other class in this conference).

Different flows within the site do different search queries.  There's actually a historical reason for that.

1 - Bidders by email - gets information around the bid and bid state.  Notice, it never says "teachers", just "classes" that are accepted.

2 - The bios page - gets BOTH - accepted Class bidders AND people who are teachers, panelists and moderators for scheduled classes.  Anything accepted and anything they are scheduled for are merged together and shown on the list.  We did this because we wanted to advertise teachers before we built the schedule.  

3 - Roles by email - is ONLY the scheduled roles - so to be a "Teacher" the person must be on the schedule (and they are teachers whether they do conference classes, drop-in classes, or master classes - but this can be further constrained later in that use case.


OK, you've combined enough stuff for 4 tickets here... so here are thoughts, but let's break this out into separate tickets with separate priorities
- First request - done, explained above.  There is no recent break here, it's just that the process of scheduling a class is esoteric and Red didn't remember it.
- **Change "Performer Items" to "Personas"** - it's easy, it's just test. BUT - I thought you hated the word Persona.  I was afraid it was too unusual a word.  Also - in the code, "Persona" is the singular performer (ie, Betty Blaize), but I can get over that if you really want it.
- **Can we add radio button at the top of each Persona page (I.e., https://burlesque-expo.com/persona/284/1/) that says "Use this persona for ( ) Acts ( ) Classes ( ) All Activity".** --- I'm confused on this.  First, I'm worried about a pretty fussy feature that benefits a serious minority of users (there 514 personas, and 500 profiles, so there are at most 14 out of 500 users w. 2 personas).  Fussy - because they ALWAYS have to choose something - the vast majority of users have 1 persona.  So we are making them do work for no reason.  Also because they can have exactly 3 personas and then I will block them from making more, because they will run out of valid choices.  Also - because I could see a user forgetting what they chose and then going to submit an act or class and figuring out they chose poorly.  Also - what about costumes?  If I don't have an "All Activity" persona, can I use one with costumes?  Lastly, this makes a use case that I find actually useful... less possible.  I have taught some classes as Betty Blaize and some as Elizabeth Kelly, depending on what branding is relevant.  So I don't want to have a single persona for teaching, I want to have more than one.  If I have "Betty Blaize - Teacher" and "Elizabeth Kelly - Teacher" - I have two that are for () Classes - won't the system yell at me?
- **Can we add a "Delete" button to the button of each Edit Persona page? I know I have some I would love to delete (Testy McTestface, for example)** - Yes - it's not as easy as a text change, but much easier than the previous request.  I do need to write a use case, but it's really simple.

**Comment by bethlakshmi** [comment]
Done, deployed and tested on live!
