### ISSUE TITLE
Allow users to "self-delete"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#257]
Sometimes someone is going to want to close their account and delete themselves from the database.  This gets tricky because of the way we relate acts/classes etc.

To solve this, we should allow people to 'delete' their accounts which actually is rendering their account inactive.

**Comment by bethlakshmi** [comment]
On reflection, if the user never got a ticket, never bid anything, never volunteered for anything - I would let them totally the delete the account as it has very little value to keeping around.  So it can work just like staff delete.  

And I do think we should withdraw them from anything in a current conference and notify the appropriate people.

**Comment by bethlakshmi** [comment]
@burlexpo - this is what I was talking about today.  It's quite distinctly "delete/deactivate" the whole account.

Not to be confused with #449 - which you wrote this year.
or #130 - which is also worth doing but which is solely focused on email

This implies that they want to totally remove the account from our system.

Thoughts?  I started on this first, because I figured the time that would generate the most deletion requests would be the time when act bids are open and we're sending out mails to bunches of people.  It's got a lot of similarities with #449, so I could redirect my energy that way if you want to think about it?

**Comment by burlexpo** [comment]
@bethlakshmi this ticket was created six years ago.  I think it has long been supplanted by later iterations of the request.  I think I would close this as "too vague, too big, and handled in part by other things we've done more recently".

**Comment by bethlakshmi** [comment]
OK.
