### ISSUE TITLE
Adding clarification to Show Reports

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#262]
When looking at the "Act Information" of a show dashboard (for example https://burlesque-expo.com/scheduling/show_dashboard/4652), there are six columns.  

It's easy to see, at a glance, if a performer has signed up for a Rehearsal Slot -- but does a blank field in the rehearsal slot mean "I haven't Signed Up for a Rehearsal", "I Don't Want to Rehearse" or both? 

Also, could we add a 7th column which says "Tech Done" and has a green checkmark if it is and a red X if it isn't?

If this is easy to do, it would be great is it could be done ASAP.

**Comment by bethlakshmi** [comment]
So, the rehearsal request is already in place... reference:

https://www.burlesqueexpo.com/scheduling/show_dashboard/4590

Your slot shows "Will not be attending rehearsal" - I think putting it in the first person ("I will not...") is pretty weird UI.  So I will do "Has not signed up" in red, and "Acknowledged No Rehearsal" as the other.

Also - I see that there is a bug - the whole row was supposed to be red font if the act tech wasn't done.  But it wasn't actually working with the various style layers.  I changed it so that (for sure) the row will be red if the act tech is incomplete.

Here's what the fix looks like...

![Screen Shot 2021-08-19 at 1 51 28 PM](https://user-images.githubusercontent.com/4542707/130119281-ece33628-a087-4973-b6a5-ad419c0418ac.png)

**Comment by burlexpo** [comment]
Yup. That works much better.

**Comment by bethlakshmi** [comment]
Pushing to live right now
