### ISSUE TITLE
On Act Decision, every event is shown

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#309]
Under where it says "Bid Control for Coordinator" (right-hand column on https://www.burlesque-expo.com/act/review/1428), is a pulldown menu which is supposed to list all the shows.  It lists every single event ever...

<img width="1680" alt="Screen Shot 2022-10-05 at 9 48 01 AM" src="https://user-images.githubusercontent.com/5369404/194077064-4046276c-ec32-44e7-a426-afb67fbb4cdd.png">

**Comment by bethlakshmi** [comment]
After we talked I did a little smoke test (see the two tickets I just made as a result. :( )

I can confirm - if you create shows for this year, you'll get only those shows and nothing else.
This ticket should stay open, though, as a lower priority, since this is super f'ed up behavior and would lead to bizarre and confusing results.
