### ISSUE TITLE
Password Reset Issue

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#31]
This may be something I did.

Caramel Knowledge contacted me saying she couldn't create a new account because of the Captcha issues.  I pointed out she already had an account and she said "But i have 10,000 email accounts and recovery on the one I _thought_ I used proved fruitless. So I'd rather start over with my most current email address." I offered to just change her email address on her account.  

I went into manage user and edited her email address.  Then she tried to use the reset password link, but got an error message saying "connection refused", so I reset her password manually.

She can login now, and may have changed her password for all I know.  She's having trouble applying, but I think that's an issue created by the DNS changeover.

**Comment by bethlakshmi** [comment]
Gotcha.

I think I found password problem.
There's a "Sites" setting in the /admin area, and it said burlesqueexpo.com which meant that the email that got sent was a crap URL.

I am fixing and retesting now... but hopeful.

It seems weird that you'd have a DNS problem with the act submit payment link.  I will also look at that ASAP just in case it's something I can debug.  We have 2 users w. that problem (check your email).  I don't know what my time is like, but I do have SOME time tonight, so banging on this as a top priority.

**Comment by bethlakshmi** [comment]
OK... I **CAN'T** fix the password reset.

The problem is that "www.burlesque-expo.com" and "burlesqueexpo.com" don't work for the password reset link.  They are only redirects and I suspect that the password reset URL isn't included in the redirect.  We need to be CNAMED.

I tried resetting our settings within django to use the domain that works "burlesque-expo.us.aldryn.io" but when I tried a test like this earlier, my settings got over-written by something.  I'm pretty sure it wasn't you, or if you did, it was in inadvertent.  I think that because burlesqueexpo.com is the primary domain in the Divio account, it is getting synced up with our Django settings.

Even if I do get the link working, we'll get creepy looking errors from browsers, because our https certificates don't reflect "www.burlesque-expo.com" and "burlesqueexpo.com" - so it reads to browsers as an untrusted certificate.  Divio will automatically fix this once we are CNAMED, but they won't update the certificate w/out CNAMEING (I just asked).

....

If you aren't getting anywhere with your registrar or DNS service, give me enough information and I'll pretend to be you ASAP... we could try a conference call to them... but I'm afraid logistics will get awful.  -- I think you have everything you should need to give them on the Divio Domains page that you set up...  the ALIAS option is a way better deal - BTW... it's easier to maintain.  But if you need IPs for an A record, they are also on that page.

... let me know which option you did, and I'm glad to ask some questions to the Divio folks...

**Comment by burlexpo** [comment]
> Even if I do get the link working, we'll get creepy looking errors from browsers, because our https certificates don't reflect "www.burlesque-expo.com" and "burlesqueexpo.com" 

OK -- so do we want the primary domain to be Burlesque-Expo with a redirect to BurlesqueExpo? Or do we want the primary domain to be BurlesqueExpo with a redirect to Burlesque-Expo?

> the ALIAS option is a way better deal - BTW

InMotion Hosting offers a redirect, but I can't tell if that's the same thing as an ALIAS.  I'll call them and try and get things sorted.

**Comment by bethlakshmi** [comment]
On the Act Payment - I just ran through it myself (I figured $4 was a cheap price for the peace of mind).

This is NOT our CNAME issues... the screens where this goes very, very badly are way past the point where the source of the request would matter.  

Here's exactly what I did and exactly where it failed:
- set up an act that would need payment.
- submitted and got the "make a payment page"
- clicked link to pay with BPT and got redirected here:  https://www.brownpapertickets.com/event/ID-6/4304003

It works.  At this point, all parts of where it came from and what our site name is should NOT matter.  Now I'm just a customer of BPT.

Next...
- 

1. I pick the $3 ticket & click "Add to Cart"
2. - I see that this will actually cost me $4.14 (kinda cheesy!!) - and I sigh and say "Check out Now"
3. - I give it a bunch of details about me (First, Last, email, phone), and I have 1 option - Pay with Paypal.  I guess if I don't use PayPal I'm screwed...
4. - I click "Pay with PayPal"


I get this screen:

![Screen Shot 2019-12-03 at 8 45 33 PM](https://user-images.githubusercontent.com/4542707/70063510-eaece100-160d-11ea-954b-63fd5eb36b9d.png)

This is where the terrible user experience begins.

First try..
- I start with "Login" to PayPal account.
- I get redirected to Paypal, I login
- I get bumped back to the page in the picture with the error "This transaction amount is greater than your available PayPal balance. To complete purchase, please add a credit or debit card.". 

That's completely inaccurate.  I have PayPal connected to my checking account.  I used it earlier today just fine!!  For some reason, BPT doesn't recognize that my PayPal account can draw from a bank.  I double checked and the account is totally fine and has plenty more than $4 in there.

Next try....

- I click the link to cancel payment and return to BPT
- I try steps 3 & 4 again
- I get back to the screen shot above
- I say "Pay with Credit or Debit Card" 
- I enter my Amex, billing address, etc.
- The first time, I am dumb enough to put my phone number in "Mobile" - I get yelled at as Phone is mandatory (this user interface is TERRIBLE... nothing is shown as required, and some fields I have successfully left blank)...  
- I uncheck "Save this information with a PayPal account" because I absolutely 100% do NOT want that. I intentionally separate PayPal from my credit cards.
- Everything is done, I click "Review"
- it says "Did you know you already have a PayPal account?"  -- YES, yes I did, you asshole, but you didn't let me use it properly ...... (sorry but this interface is awful)
- I select "Continue without logging in" - note that there is a big white square on top of continue.  It also makes it really hard to click on.  I basically could only click it by hitting the capital "C" because of this bug.

![Screen Shot 2019-12-03 at 8 54 19 PM](https://user-images.githubusercontent.com/4542707/70064205-20de9500-160f-11ea-999b-42eafaee1d02.png)

- I get another confirmation screen, I click "Pay"
- I get an Error.  Nothing specific, but it takes me to https://www.brownpapertickets.com/browse.html
(yeah, not even our ticket link... good luck users)

![Screen Shot 2019-12-03 at 8 58 00 PM](https://user-images.githubusercontent.com/4542707/70064498-a2cebe00-160f-11ea-9dad-1e4c220eeda4.png)

-----
I also read the site html and several pages in there is no reference to the source that directed the user to BPT.  

Please escalate this to them... I don't think that even if we have the domain name right, this will ever work properly without them doing a hell of a lot of bug fixing.  I wrote a ton of detail here, in the hopes you could just point them to this and say "fix it".

If you need to change payment systems, let me know - I can't write that kind of code for our end super fast... it's not an easy ask, but this is a terrible user experience and I would be happy to do anything that made this better for people.  Chances are, I couldn't push code until I'm nearly home, but better that than this.

Alternately... if you want to take money manually via PayPay transfer to your account, I can show you how to splice in the user data to the act-submit side of our system super fast, and I could grow you from easier and easier manual input to something that might be automatable eventually....

**Comment by burlexpo** [comment]
The problem is with PayPal.  I'm dealing with it.  It's not a code issue.

**Comment by bethlakshmi** [comment]
Ah. OK. Good.  Password reset is happy now.
