### ISSUE TITLE
DNS Redirect Weirdness

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#32]
I'm pulling this off the password thread because it may be a separate issue.

I modified the A NAME records for Burlesque-Expo.com at InMotion Hosting with the info from Divio.  Now when I type in www.Burlesque-Expo.com I get taken to the new site without problems, but the URL displayed on the page is https://burlesque-expo.us.aldryn.io/main/ 

I suspect that's still going to give us security problems.

**Comment by bethlakshmi** [comment]
OK... will escalate w. Divio.
When did you set up the A NAME record?

**Comment by burlexpo** [comment]
About 3 hours ago.

**Comment by bethlakshmi** [comment]
Also - did you do burlesqueexpo.com as well?

**Comment by burlexpo** [comment]
> Also - did you do burlesqueexpo.com as well?

No.  I need to figure out who the domain manager is for that.

**Comment by burlexpo** [comment]
Ok -- found it and changed the A NAME per Divio's instructions.  DotEasy says it may be 24 hours before the change propigates.

**Comment by burlexpo** [comment]
And now when I try "burlesqueexpo.com" I get redirected to Divio -- but I still get  https://burlesque-expo.us.aldryn.io/main/ at the top of the page.

**Comment by bethlakshmi** [comment]
OK, I'm going to make burlesque-expo.com the primary.

What I'm seeing when I test is that there are 3 records for burlesque-expo.com:

Name:	burlesque-expo.com
Address: 54.227.157.72
**Name:	burlesque-expo.com
Address: 198.46.90.135**
Name:	burlesque-expo.com
Address: 34.238.97.72

The one in the middle is NOT a Divio record.  There could be two reasons:
1 - you need to remove this from the InMotion Hosting
2 - it's still updating

It's promising... the other two records are the Divio IP addresses... so that's good.

I'll give it another 12-20 hours and check again - if it looks good, I'll start pushing Divio to see what is going on there.

**Comment by burlexpo** [comment]
I went back to InMotion and deleted the entry for burlesque-expo.com that had that IP address attached to it.  There are a _ton_ of other records that use the 198.46.90.135 address -- notably stuff like mail.burlesque-expo.com. but also weird (to me) stuff like autodiscover.burlesque-expo.com.

**Comment by bethlakshmi** [comment]
![image](https://user-images.githubusercontent.com/4542707/70111472-48b61300-1678-11ea-9427-514aa3f9be1f.png)

That's a very good sign - it looks like Divio agrees that BOTH names are CNAMED.

I'm testing and I see that even when I start w. www.burlesque-expo.com - it defaults back to the Divio name.  I'll ask if there's a way to change that... 

....but there may not be, and I don't think that Webfactional worked that way either... I think that w. WebFactional, after going to www.burlesque-expo.com, you would get to their made-up-name for us (gbelive.webfactional554.com or something).

Password reset test WORKS!  

Also - security errors stopped - because I think they have an HTTPS cert set up for us (they are so slick, I'm kind of jealous)

**Comment by bethlakshmi** [comment]
https://docs.divio.com/en/latest/reference/addons-aldryn-django.html#domain-redirects

Got help from Divio.  Sharing link in case I don't get to work on it today and it makes sense to you... I suspect not, I suspect it needs django expertise.

**Comment by burlexpo** [comment]
Yeah -- I read it.  Gibberish to me.

**Comment by burlexpo** [comment]
Ok -- so this is more weirdness.  If I'm not logged in, and I type in **https://**www.Burlesque-Expo.com, I see www.Burlesque-Expo.com in the URL bar.  If I just type it in without the http (so just www.Burlesque-Expo.com or http://www.Burlesque-Expo.com or Burlesque-Expo.com) I get https://burlesque-expo.us.aldryn.io/main/

**Comment by bethlakshmi** [comment]
This is all part of the link I sent - the server presents the project's core DNS by default in all sorts of circumstances.  Honestly - this is all in their server/networking - so I don't have a great grip on all the particulars and I'm not sure if I can fix all of the branding here.

For the record - there were plenty of times with WebFactional where the URL bar showed WebFactional's default DNS, too....

**Comment by bethlakshmi** [comment]
This is old, long, and I think inaccurate now.  Opening up a new ticket for current state next steps.
