### ISSUE TITLE
Link in email to Act Reviewers doesn't work (for me)

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#333]
This is really minor, but I wanted to get it on record and to show I'm not crazy.

In the attached screen recording, I'm clicking on the link (which is why it's flickering), but it doesn't go anywhere.  That's in Mac Mail and my default browser is Chrome.

https://user-images.githubusercontent.com/5369404/201766106-e9247f4f-4af0-460d-b707-2c1201f07a15.mov

**Comment by bethlakshmi** [comment]
WE FOUND A FIX!!!!

All email links MUST use "http://" to invoke the URL.  Email browsers (at least some of them) will not consistently interpret <a href="www.something.com/whatever">link text</a> as the trigger to open a web page.

Rather than splice this into every template, I'm going to change the code to make any URLs given be given with that http://

**Comment by bethlakshmi** [comment]
Deploying now.  Will be in place before next batch of Act Tech reminders.

This was a manual review - meaning I fixed anything that looked like a link, and added "http://" to it.  I'm not perfect.  

So if we get reports of a link not working (other than the password reset link, which is broken for a different reason and already has a ticket) - then we should write a ticket.  At that point, it will help to have specifically what email has a broken link and what the broken link is.

For sure, I fixed the act reviewers link that is the start of this ticket.
