### ISSUE TITLE
Cannot Create New Accounts

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#34]
If I go through and create a new account, click on CAPTCHA, everything is fine.  If I click “SUBMIT” I get a SERVER ERROR (500)

The problem is NOT with CAPTCHA.

**Comment by burlexpo** [comment]
Tested it 3 hours later.  Same problem.

**Comment by burlexpo** [comment]
Test #2, 11 hours after Test #1 (14 hours after initial test).  Still no go.  @bethlakshmi I know you're on vacation, so if you can point me towards someone to yell at at Divio, I will yell at them.

**Comment by burlexpo** [comment]
More info:  Sabrina Strauss (sabrinadelarouge) seemed to be able to create an account sometime around Dec. 2, 2019, 11:17 p.m. -- so the server error started after that.

**Comment by bethlakshmi** [comment]
I GOT IT!!!!  AHHAHAHAHAH!

Did it in under 10 min so I'm kind of proud of myself.  The problem was kinda ugly and not one you could fix.  The issue was that when I did the database port, I didn't set a counter value properly on the new users table.  I caught this issue and fixed it in other places, but not here.

As such, it had a very low value that it +1's every time a new user enters... but eventually it came up against a value that already identified a known user and that caused an error.

Once I updated the counter to be higher than the highest known user, the 500 error disappeared and a new users was made.  

Before I close, I will go back and review everything else to make sure I didn't make the same problem elsewhere.  But you should be able to tell users we fixed the problem.

**Comment by bethlakshmi** [comment]
Checked in the car on the drive today.  Can't find any other cases.
