### ISSUE TITLE
Add Social Media (Pt 2) 

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#344]
Generate slides for projection in shows.  Slide specs are

- slides are 16:9 ratio
- include performer name in a display font
- include top 3 links from profile
- include Expo logo

See example (attached)
![Performer Slide](https://user-images.githubusercontent.com/5369404/209849623-924a98d0-768d-4354-a345-777165c68c1b.jpg)

**Comment by bethlakshmi** [comment]
Note to self - http://0.0.0.0:8000/act/review/1515 - performer review used to include website and should now include list of social links.

**Comment by bethlakshmi** [comment]
I'm gonna start this now - I want to at least get the website view/bid review side done relatively quickly, so that when excited performers advertise for us, the links show up on the website where we said they would.

If it takes longer to make the slides - I'll do that PR second since we don't need until the week before the show.

I'm thinking (in both cases) of seeing if I can use some cute logos where appropriate - like the twitter bird, the paypal P, the Cash app $, etc.  And - on the website, their username - with a working link.  On the slide - MVP is the full URL.

Super duper sexy would be a scannable QR code that takes you to a mobile app sized link page on our website with all the links, so that all you do is scan and click you don't have to thumb type anything in.  I'd do both (QR code + text URL) in case the QR code can't be scanned at a distance.  That's the stretch goal.

Is there a perferred slide deck format?  Google Slides?  Power point?  Just a series of JPGs?

**Comment by bethlakshmi** [comment]
![Screen Shot 2023-02-04 at 8 18 58 PM](https://user-images.githubusercontent.com/4542707/216796651-f9790d58-b7f1-417a-93dd-ceda735ee502.png)

Ta-dah!  I plan to reuse this in the teacher page, the performer blurbs (show here) and when the bio is part of a bid review.

**Comment by bethlakshmi** [comment]
Leaving open until I have a slide show making mechanism.

**Comment by bethlakshmi** [comment]
But it is now OK to advertise this feature to performers - they can put in their links and see it online.

**Comment by bethlakshmi** [comment]
OK, the slide deck thing is not easy.  I haven't given up yet, but I'm trying to figure out how to do it most easily, since this is the only slide deck making feature we have right now.

So... questions:
**- do we have a particular format for the slide show to be displayed with?  Or is any common tool set OK?**

Right at the moment, I'm leaning towards a PDF.  I figured out that there's a well known library for making PDFs with Python, hence django.  And I figured out that Preview (Apple's PDF viewer) will let me view a random PDF as a slideshow with the features that one might want (like using the arrow keys on the computer to move it forward/back.  

A minor plus - a PDF is a pretty reusable tool.  We do a whole bunch of reporting where PDFs might be nice.

Downside = PDFs are not so editable by the average computer - you'd want to regenerate the PDF on the website if the order of performers changes.

**- is edit-ability a big deal?**
There are APIs for making google slides and I believe PPT.  I _think_ that that would end with a slide a person could edit easily if something was off - say we change performer order, or there's some minor tweak.

The downside - more work for me.  The APIs are a whole new space, and not as intuitive to me as the PDF report generator I found.  Also - this gets us Google Slides *or* Powerpoint - they can be converted between each other, but my code won't do both.

**- how much work can we make the user do?**

I'm finding some stuff that suggests there are ways to generate slides from a CSV or spreadsheet.  That would let a user (you, me) make a template like what you want in Google Sheets or PPT and then fill it with the data.  The website would give you the CSV of the data.

Pros:
- very easy for me.  CSV writing we already do, so there's virtually nothing I need to learn on this.
- template is customizable in a normal way by more than me - so if the logo wants to change, or we don't like a font - this isn't a code change.
- (probably) editable after creation - user can change text on slides or slide order on the fly.

Cons:
- more work for user.  There's actually a procedure involved to get from data --> slide show.  I could do it the day before the shows, or teach others.  This is an "advanced user" kind of thing, which is always a little hard to judge.
- May need user to install something on their google account - a free plug in. 

**-Powerpoint vs. Google Slides**

Microsoft office on a user's laptop is becoming rarer and rarer.  Google Slides is free and always on the web.

I'm assuming Google Slides is preferred - but the only limit here is network access.

Is that all good?

**Comment by burlexpo** [comment]
**FORMATI** think individual PDFs are good.  If you open multiple single page PDF documents with Preview, you can change the order they are in just by dragging them around in the sidebar

I'm not a fan of PowerPoint for this.  It seems like way more than we need.

**Comment by bethlakshmi** [comment]
We talked today - i'm going to end this with a fast CSV to make a table with:
- performer name
- URL1, URL2, URL3 - if there are < 3 URLs, some of these columns will be blank

This should be quite mergeable into whatever kind of slide template we want.

**Comment by bethlakshmi** [comment]
[The Main Event_perf_urls (2).csv](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/files/10714654/The.Main.Event_perf_urls.2.csv)

Here's the csv I'm planning on - 1 per show, filename is based on show name.
