### ISSUE TITLE
Filter Acts by Show Interest

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#348]
Set up some checkboxes so Scratch can see who is interested in performing in which shows.

If it turns out that you can't do this before Feb 4, don't worry about it.

**Comment by bethlakshmi** [comment]
Based on our talk and more thinking - I stand by my original thought... this would be server side:
 - the page would offer a set of checkboxes (1 for each interest - ie bordello, star bras, main event - competition, main event - not for comp, etc) & a button.
 - That would work as a Form Post to the server, who would filter all acts to any acts with any selected preference.
 - That supercedes the JS table with its search field.  That search won't get you anything the checkboxes filtered out.
 - Checking them all or unchecking them all works the same way - it gets you everything, because we require you be interested in at least 1 thing.
 - Show only on current conference - because we have changed the choices for interests, they are not backward compatible to previous years.

This should be ~1 week of work.  Saying 1 week just cause I'm not at a perfectly efficient cadence recently so I'm giving some slack.

**Comment by bethlakshmi** [comment]
![Screen Shot 2023-01-05 at 1 20 22 PM](https://user-images.githubusercontent.com/4542707/210852420-391af0a9-75a4-46d9-b51d-5081d6829c11.png)

Nothing works yet, but how's that for look and feel?

**Comment by bethlakshmi** [comment]
OK, another edge case-y question - 

For normal people, we require that the user pick at least 1 show preference.  However, if the Act Coordinator made an act for someone and submitted it immediately, that act won't have any interest attached to it.  This creates a vector for creating acts with no show preferences.

When filtering - should empty acts be...
- filtered out of any show preference choice? No preference = never show on filter
- included in every filter?  No preference = prefers everything
- have it's own filter - because these are special acts and the act coordinator may be saying "where's that special thing I made???"
- prevented entirely - add the show preference as a requirement to submitting an act via the special thread.  Now it's always there, and this edge case never happens

**Comment by burlexpo** [comment]
I'm OK with either "included in every filter" or "gets its own filter".  I don't like making a preference a requirement.

**Comment by bethlakshmi** [comment]
OK, I have it working in my local.  Is this worth it to put on the test server for experimentation while I'm setting our regressive tests?

**Comment by burlexpo** [comment]
NO, I think it can go straight to Live.  If it doesn't work there, I'll let you know

**Comment by bethlakshmi** [comment]
deploying now
