### ISSUE TITLE
Email sends multiple copies of things

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#35]
I sent out an email using the "Contact" function.  I sent it with the attached filters, and it apparently sent 7 or 8 copies of the email to at least two people.  My guess is it's not checking for duplicates, but I'm just guessing.

<img width="1440" alt="Screen Shot 2019-12-07 at 9 34 53 PM" src="https://user-images.githubusercontent.com/5369404/70383296-754c8200-1939-11ea-8bc9-2f0e2b5f10bc.png">

**Comment by bethlakshmi** [comment]
It absolutely DOES de-duplicate.  100% I built that in.

OK, so I'm sick (sore throat), and have been running around to get ready to go to Hyderabad tomorrow.  On the plus side - that means I have 2 hours or so in planes or airports hopefully near some wireless.  On the minus side, I don't know what Hyderabad timing will be like.
I've been digging on the site, and here's what I have so far ...

- Fixed a deployment problem that blocked redeployments - it was a random update of one of the underlying libraries that had an impact.
- Definitely the cron is off and the emails should have stopped sending.
- I tried to set up the same test on the test server, where the person I will spam the crap out of is me (because I put some controls in to avoid sending test data to real people).... Here's what I did:    
     - picked "Send by Role"
     - picked every conference
     - picked only the Performers
     - wrote a quick subject line and short message
     - sent it

And the damn thing works.  i got all the mails.  Once.  They all sent and then got marked as sent (the emails this morning in the heat of the problem were always in the "queued" state), and each email was only sent to me once.

ARGH.  So I can't simulate this on test...  

**Is that what you did?  Any chance you have a copy of the text you sent?**
** what users reported a problem?  did their names start early in the alphabet?**

Symptoms of problem:
- you told me users were getting multiple copies, but according to the data state, NO email had yet been sent from that batch.  When an email is sent, the library moves it from "queued" to either "sent" or failed" - they were all queued.
- but obviously some mail got sent.  Numerous times (when each user only gets 1 mail in my code)
- So... theory is - the system sent mail, and then got screwed up at marking that the mail was sent.  This isn't in my code this is 100% a separate library so adding debugging is not an option.
- When it woke up 10 min later, it did the same thing again.  It always starts with the first set of users... so it always hit the same people over an over again.   
- It DIDN'T hit me - I'm one of the performers but I got NO mail.  So it screwed up before it got to me.


**One idea** = set the batch size.  The tool we use (Django Post Office) says that's good for low memory (? not sure that's us?) - setting a size of 50, for example, would mean that a big batch like this takes probably an hour to all get sent, but it means that updates are smaller.

**Another idea** = buy more RAM - I thinking about proposing this anyway.  The site support recommended it, and we're at about 1/2 of our RAM usage.  We don't want to be too much higher.

**Third idea** = dig line by line into the django post office code to get the specifics of the error - based on what I see in the database, it looks like the email sender was dying after the mail was sent, but before the tool updated the database.

If we do #1 or #2 ideas - I'll want to watch this as you use it the next time... which means we need to set a time to run this together.  I generally have before 10 AM India time, and after 8:00 PM...  it's hard to predict past that... but also 10AM is 11:30 PM EST, and 8 PM is 9:30 EST - so these are also best bests for India/US coordination.

Thoughts??

**Comment by burlexpo** [comment]
For the email I sent, 

- I selected "Contact **Bidders** By EMail" (you selected contact by **Role**, not sure it makes a difference, but it's a difference between what I did and the test)
- Selected all available Conferences
- Selected _Act_ as Bid Type (and no other bid types)
- Selected all _States_ **except** "Draft".

I got email from 3 individuals complaining about the issue (I don't know if other people had the issue):

- Satine S'Allumer (satine.sallumer@gmail.com) says she got it 8 times
- Veronika Winters (veronikawintersburlesque@gmail.com) says she got it 7 times
- Trixie Paprika (trixie.paprikas@gmail.com) says she got it 11 times.

They are neither the first or last on the list, and they're not even sequential (assuming the folks in between them didn't have the issue).  I was wondering if it had something to do with the single apostrophe in Satine's last name, but there's no apostrophe in her email.

**Comment by bethlakshmi** [comment]
Hm... don't see a pattern either.

Did Veronika want to be deactivated?  In my test run, I don't see her email...

When I try this on staging with the exact same data as live and your flow - these are NOT the first emails to be sent...  and unfortunately (fortunately?) my staging tests still work exactly as planned.  Only live is being a problem...  ARGH.

OK, I dug into the code as far as I can figure out... I found:

- by default, it uses multiple threads to send the emails... but the multi-threading has some notes around forking processes and database connections - no wonder, that is always tricky to handle.  Given the comments in that section of the code, I decided to turn us down to a single process.  These emails don't have to go in a hurry.

- the logic is: 

    1.  get a batch of emails (depending on batch setting + emails to be sent + # of threads)
    2. proceed to send each email, get it's status and keep in memory
    3. save status to database when ALL emails in batch are done (as a bulk update).

That means that if step 2 fails mid-flight, mails get sent, but status doesn't get saved.  Which sounds like the problem we have.

.... so I also set the batch size to 30.  And slowed the cron job WAY down - every 30 min instead of every 10.

I'm running a test cycle now - with an email just to the two of us.  

If that works - what other email do you want to send as a batch to people?  I would like to do, and supervise a test run.  If you send me the copy for what you want, and tell me who to send to... I will run it and let you know the results.

I can't think of another way to test this, given that test server isn't showing any problems.

**Comment by bethlakshmi** [comment]
In my test email I say it'll take 14 hours for 210 emails.  Math was wrong - it would take 3.5 hrs.  That's not too bad... and I can probably leave that as is for some time.  My concern is always the daily schedule emails - because those go to a lot of people but really need to go the night before.... so if they take 12 hours to send, that's a real problem...

**Comment by bethlakshmi** [comment]
Email worked!!! This has GOT to be a large size problem.  Please give me something I can send to a batch of users.  I really need to monitor my new settings and see if they are OK.

**Comment by bethlakshmi** [comment]
Trying my first batch of 10 on the performer emails (put in queue on Dec. 16, 2019, 2:42 a.m.)- 
- picked ALL conferences EXCEPT GBE2020 (figure they already know about us)
- Acts
- all statuses
- put in "info@burleque-expo.com" as the sender so that it's as if @burlexpo sent it.

Keeping track of who I sent to in a spreadsheet offline.  If 10 works, next batch is 20 and so forth.

Will keep running tally in this comment so we know where we are...

**Comment by bethlakshmi** [comment]
OK!  We got a FAILURE!!!

Different behavior (I think) from before.  And I don't think any users would have seen the errors.  But with the weirdness last time, I can't be 100% sure.  But at least this time, I have a list of the users in this batch and I'm grabbing a copy of the data on the test server so I can look more closely.

The error from the In Motion company is:

(550, 'This message was classified as SPAM and may not be delivered.  For more\ninformation, please see http://www.inmotionhosting.com/support/edu/everything-email/550-spam-message')

On **all** the failed email messages (all 30 in the first batch).  After that, all messages were listed as queued, and the end of our cron was a failure status code.  My bet is that NOTHING got to an actual user.  I'm deleting all the queued messages, so we don't have a repeat of the last time we had this issue.

Looking at the InMotion checklist on the URL above:

- **Solution #1 – Enable SMTP Authentication in Outlook** - we obviously don't use outlook.  But we DO use SMTP.  Just checked!
- Solution #2 – Evaluate email content - I took a look [Hubspot's](https://blog.hubspot.com/blog/tabid/6307/bid/30684/the-ultimate-list-of-email-spam-trigger-words.aspx) guide - they are a company I worked with professionally, and I trust them to be pretty darn smart.  Nothing sticks out to me.
Solution #3 – Contact Live Support directly - **think this is where we are...**  you have a copy of the mail... although if you want a direct copy - https://burlesque-expo.us.aldryn.io/admin/post_office/email/770/change/?_changelist_filters=status__exact%3D1

Can you reach out and see?  I suspect what happened is that with 150 mails of the same content in 1 day, we hit some sort of trigger.

**Comment by burlexpo** [comment]
I wrote to inMotion and had our email limit lifted.  Prior to this we could only send 50 per hour.  New limits are "You can send up to 250 emails per hour for a total of 6,000 per day. Just set your Email software to send within those limits and you should be fine".  Do I need to contact InMorion hosting about something else?

**Comment by burlexpo** [comment]
This email reached at least one user (Dolly Debutante -- dolly.debutante@gmail.com) because on 12/16 she replied to the email asking to be removed from the list.

**Comment by bethlakshmi** [comment]
Yes.  It reached 150 users!  I have been doing ever increasing batches as listed above.  Dolly was in the early batches.

It is now failing on 125 of our remaining emails - roughly from the middle of the "m's" to the end of the alphabet.

OK... hopefully if I get time tonight, I can requeue that last batch oy-oy-oy-oy-oy.  GRRRR.

(at least the coffee here is wonderful)

**Comment by burlexpo** [comment]
I got the mail logs! I don't know how useful they're going to be, but here they are.
[20191201-20191208.txt](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/files/3979122/20191201-20191208.txt)

**Comment by bethlakshmi** [comment]
Woohoooo!

After you got InMotion to fix their end, I tried the last batch of 125 emails.
The first round has worked sucessfully (~90 were sent) - the other 33 are in "queued" state and should ship out in 1/2 an hour.  I will likely be on the roads of Delhi by then ... but I'll check on it. 

Will dig into logs later.

If that last 33 go no problem, I'll close this ticket assuming my tuning of our email system worked.

Current tested rate is that:
- cron job kicks off every half hour
- with a high load, it takes around 12 minutes to run
- it will send up to 60-99 mails in an iteration

Which means:
- I *could* increase the frequency of sending to every 15 min.
- I'm not too worried about sending the daily schedules.  They would go out w/in an hour or two of being sent.

**Comment by bethlakshmi** [comment]
WOOHOO!  All is sent!  I think we're past the worst.  
But next time you send over 60 messages, give me a heads up w/in 10 minutes of sending so I can monitor.

**Comment by burlexpo** [comment]
I re-opened this.  I'm not sure it's the same cause, but it's the same symptoms.  I (Scratch) am getting two copies of the Mail that is automatically sent to Act Reviewers when someone successfully submits an act.  I assume Betty and Scarlett are also, but I can confirm.

**Comment by bethlakshmi** [comment]
Nope, haven't noticed it.  But I do see 2 emails for an Act Submission by Tapitha Kix (in quick succession, this morning), and 2 for Luscious Lane (but spaced out quite a bit in time.  Luscious Lane actually submitted two acts, so I think that's normal .  Tapitha, however, has only 1 act submitted...

Digging into that for a few until I hit the office, but there's been no code change recently and Tapitha is the only case I've found so far... if you have others, having the performer name would be helpful.

**Comment by bethlakshmi** [comment]
OK - see two for Private Tails, as well.

**Comment by burlexpo** [comment]
I'm closing this again.  We did have some recent email issues, but people complaining about duplicates weren't amongst them.
