### ISSUE TITLE
Act Review #s

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#366]
Two related enhancements

1) If you're a member of the Act Review Committee, it would be great on your dashboard near the list of acts to review, it said "You have X acts left to review of Y total acts".  That lets people know where they are 

2) It would be great if you're the Act Review God (or whatever the Act Review Ubermensch is called), if somewhere there was a summary of the above information, i.e., when I look at the acts to be reviewed, above the list I also see

Scratch: 100/137       <--- where that means "Scratch has reviewed 100 out of 137 acts"
Scarlett: 99/137
Willy: 70/137
Lady Sapphire: 0/137

Unless this is super-easy to do and can be done in the next week, don't worry about it until after the BurlExpo.

**Comment by bethlakshmi** [comment]
![Screen Shot 2023-01-19 at 7 34 36 PM](https://user-images.githubusercontent.com/4542707/213592647-b718fca3-057e-4d09-9610-120213cfe28a.png)

Right now - reviewers all get this.  I have always thought that was overkill.  How about I do a "you have reviewed X out of Y acts" message here instead, and color it yellow if you need to do stuff, and green if you're all good?  This is on the user's home page, bottom right.  Let me know if you want me to move it?

For the Act Review God - how about a box at the top right of the act review screen (under the comp acts button).  Visible to everyone, since there's nothing secret here.  People can use it as an additional metric to see what's left.

I'd do it for any bid review (Vendor, Costume, Class... not volunteers) if there are reviewers, if there's only a coordinator, I'll skip it.

**Comment by burlexpo** [comment]
That all sounds perfect

**Comment by bethlakshmi** [comment]
<img width="524" alt="Screenshot 2023-10-15 at 2 17 29 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/59d328b3-8ed6-401c-9908-0e3cdaac9936">

This is done and was quite easy

Now working on metrics for the act for all revewiers on the act review list page.

But if this is a big enough win for all - could pr what's done so far ASAP if desired.

**Comment by burlexpo** [comment]
@bethlakshmi I like it! Will definitely help with real estate on my dashboard
