### ISSUE TITLE
MAIL change batch rate

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#381]
We need to set our batch rate so we don't exceed 700 messages in an hour. I think you have to do that on Aldryn.

**Comment by bethlakshmi** [comment]
Argh.  This is not that easy.

We have batch size set (to 30)
We run the cron job every 30 minutes.

But the way that post office is built - there is no way to pause between batches.  Its logic is - get a batch of queued mail, send it, repeat until you run out of mails. 

So if we queue 800 mails, it will send 800 mails, single threaded in batches of whatever size I tell it, until it's done.

I can tune the batch size down to 1 to try to be as inefficient as possible, but that will still probably be too efficient since there is no sleep in this cycle... I would have to break into post office to do it.

**Comment by bethlakshmi** [comment]
This is coming from "send everyone" right?  That's sending to **everyone** who ever had an account with us, unless the account is deactivated, or they chose to turn off email sending on their account.  It's the single biggest set of email you could ever send, and by a very large margin.

The subset of anyone who submitted anything this year is MUCH smaller (86 people).

My alternatives are all ugly but here they are:

- I write my own queue on top of their queue.  This gets messy and the professional me knows that I will regret this.  The mitigation is that because there is largely 1 user of this system, the things that usually go wrong in this kind of solution probably won't go wrong, because we won't be doing the stuff that usually breaks.

- Be mean to the user (you) and fail at you if you are going to break the 700 rate limit.  Much less bug prone, but kind of painful.  It utterly blocks you doing "email everyone" unless I give you also a way to "email half of everyone" and "email the other half of everyone"... kind of like a sort of email pagination.  That offers the same kind of failure but on a human scale.  Humans are not better queuing systems than computers.

- See if I can refactor "email everyone" specifically to be a multi-recipient BCC format.  I believe in that way, we'd be sending only 1 email for X recipients, and that would keep us under the 700 limit with your mail service.  We'd have to test it, BCCing may be a trigger factor for your service just as much as 700 emails/hr is.

- See if there's another email filtering scheme you'd like other than "email all people who ever had an account"?  For example, maybe a filter for "people who have logged in in the last year?".

**Comment by bethlakshmi** [comment]
Oooh!  Thought of one other solution - if it was possible to get the mail service to reject emails over its rate limit, but NOT cut us off completely forever after that.... we could requeue mails and resend them.  We could then tune our mail sending down to once an hour... whatever fails fails.  Then our system requeues failed mails, and sends an hour later.  At the rate we are currently operating, we will always have 2-3 hours for the dust to clear between batches... 

We could also throw up a warning condition when we're operating in this kind of load, that shows up on any bulk send page, that says "come back later, system is under heavy load" so we know that that's happening (and if it lasts for weirdly long, we can investigate)

**Comment by burlexpo** [comment]
My impression was that there was a gating tool or setting somewhere -- no?

Also, as we get more and more successful (hopefully) more and more cases will edge closer to the max mails per hour.  Counting on lack of sign-ups to be our gating tool seems like a bad plan...

**Comment by bethlakshmi** [comment]
Hmm... in trying to prove it couldn't be done, I think I found another
setting:

https://github.com/ui/django-post_office

Does have something called "scheduled_time" - that's still not an explicit
rate limiter.  I'd have to put in some logic when queuing emails to see how
many are in the queue and to set up a time schedule if there is too many
for the next hour... something like:

- what is the latest scheduled time?  How many mails are scheduled for then?
    - put as many less than 700 as possible into current last time
    - repeat putting up to 700 mails into the queue at + 1 hour batches
until we run out of mail to send.

Then the scheduler should:
- pick up all the queued mails to be sent before now.
- send them
- sleep

And leave the other mails not yet ready to be sent alone.

A bit crude but it's actually not a queue, just a schedule...

But the stuff you are thinking of was about limiting the ability of the
system to overuse it's server's resources - which I've already done.  There
appears to be no way to keep it from overusing the mail server's limits.

**Comment by burlexpo** [comment]
Never mind.  I think I can do this from my controls.
https://docs.cpanel.net/knowledge-base/email/how-to-set-email-send-limits/

**Comment by burlexpo** [comment]
Never mind the never mind.  That's the tool they use to regulate the rate that we're violating...
