### ISSUE TITLE
Conference Volunteer shifts show up on Conference Calendar/Room Labels?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#417]
If you take a look at https://www.burlesque-expo.com/calendar/Conference?day=05-06-2023 at 9:00am, in the first column, you'll see "Conference Helper".

Also, not sure if it's a realted bug, but didn't we display toe rooms of the classes on the schedule? Because we don't now.

**Comment by bethlakshmi** [comment]
Yes.  This is because you have a staff area with a slug called
"Conference".  Both the labels for the calendar and the staff areas use the
same set of tags so that I have a consistent place to filter.  "Conference"
is the slug I associate with all conference classes and that's how I search
to make stuff show up.  I didn't realize you were going to make a staff
area like this.

I just changed the Conference staff area to use the slug "Conf_vol" but
unfortunately, changing the slug does not change all the tagging on all the
events in the database, it's going to have to be a manual update.

I will do that when I can, and I will use this ticket to make an error
check on staff areas so that they can't use slugs that are reserved for
other searching in the system.  In fact they also should not collide with
each other.

-Betty

**Comment by bethlakshmi** [comment]
Tackling this today because I'm pretty sure I don't have the brain space for anything more complicated.

**Comment by bethlakshmi** [comment]
Deploying now.  Hopefully I got it in before the cron executes the Act Tech reminder email today.
🤞
