### ISSUE TITLE
Volunteers and Rehearsal blocks

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#465]
_NB: This is "High Priority" -- what I mean is this is important to be done by the milestone, not that it needs to be done now._

There are some volunteer shifts that are associated with shows where the volunteer really needs to be at the rehearsal as well.

This means we need:
- some way of associating two different volunteer shifts such that signing up for one automatically signs you up for the other.  This should probably be a two-way relationship (i.e., if you sign-up for the stage itten rehearsal slot, you get assigned to the stage kitten show slot -- and vice versa).
- removing a volunteer from one removes them from the other
- volunteering for one of the paired slots throws up a big acknowledgment panel which says "HEY! You're signing up for two different shifts!" and the volunteer has to click "Yes, I get it"
- Some of the volunteer aspects of one shift match the other (i.e., required approval, number of volunteers) but not all (duration, start time)
- the volunteer shows up on reports in both places
- the two different shifts show up on the Dashboard for the volunteer

**Comment by bethlakshmi** [comment]
Interesting.

The same paired concept exists with performers & shows/rehearsals.  The
business logic is different - performers self-register for rehearsal, and
removal coupling only goes one way (remove from show does mean remove from
rehearsal, but remove from rehearsal != remove from show).

Makes me think there may want to be a way to couple two scheduled events.
And then build the logic around the coupling.

In the case of volunteering - I'm thinking that:

- the two shifts share - the title, description, # of volunteers needed,
and the approval needed status.
- but they have 2 different times, 2 different durations

Also with volunteering - we have a few different signup spots -
- the volunteer calendar - which gives a popup, and then submits the
request to volunteer - a popup w/in a popup gets cumbersome - but it could
have a very explicit warning manner saying "volunteering for this is
volunteering for TWO time slots...."
- volunteering from the list/event details pages - where it makes sense to
have an additional popup saying "this is two shifts..."

And I'm thinking that if a volunteer drops, the email to the staff lead
notifying them also notifies that BOTH shifts were dropped.

**Comment by bethlakshmi** [comment]
starting this while I wait on nav design, and on a few days before PR-ing the troupe setup thing.

**Comment by bethlakshmi** [comment]
Looking at what's easy with the data - building a link between two events is quite easy.  Trying to refactor for shared data between two linked events is less easy. 

So my proposal here is:
- set up a "peer" link between two events - it's different from the parent/child relationship in that the two peers are equals, one is not a part of the other.  So deleting one does not mean the other is useless.
- let the scheduler set up a relationship between any two volunteer shifts.  Technically the link can between any two events, but in the UI, I'm going to limit it to places where it's useful.  Namely:
     - the volunteer event scheduling page:  **example**:  http://0.0.0.0:8000/scheduling/volunteer_edit/GBE2023/4916? 
     - the list of volunteer events inside a show:  http://0.0.0.0:8000/scheduling/show_edit/GBE2023/4830?
     - ... in a staff area: http://0.0.0.0:8000/scheduling/staff_edit/27
- in all cases, it'll be a searchable box that lets the user search by the staff area title and/or parent event title and/or staff area.  When the results of the search are shown, I'll make sure it is the format:  "<staff area> - <parent title> - <title> - <date & time>" - since that's what we need in order to disambiguate... I think?  When the choice is made, it'll show something shorter to not distort the form (maybe just title, or title & day/time).
- The search is limited to events in this conference.  But it will include ALL volunteering events - even if the user does not have access to editing volunteers in a given area...  otherwise, I think it gets messy - say if Scratch with infinite access sets something up, and then Mike with less access edits something but can't preserve a linking because he doesn't have access... etc, etc.
- update the summary on the event search/manage page to show an event's peer.
- Any time an event is shown to volunteers, the dates and times of BOTH events are listed.  
- Adding/removing staffing always removes the volunteer from both slots.

Questions:
- right now I'm limiting this to two events.  I.E. Event 1 and Event 2 can be paired, but that means that Event 1 and Event 2 can't  be paired w/ any other event.  Technically in the data model, it's possible, but for display & simplicity, I'd like to keep the assumption there's only a pair, OK?

**Comment by bethlakshmi** [comment]
Some nuances I'm thinking through:
1 - copying - should the pairing relationship be copied when a group of events is copied?  it gets kind of tricky.  Seems like I should be able to do it, but will need to keep track of what's been copied to avoid making duplicates.

2 - one paired event is full, the other is not.  Should I deny access if only one is full?  Right now, I'm just going to assume that this is rare, and that the person making the pairings is paying attention to the # of volunteers per event.  It'll assign the volunteer to BOTH events if the targeted part of the pair has space.  Example - follow spot has both a rehearsal event and the during the show event.  The rehearsal slot has 2 volunteer positions allowed, the show event has 1.  Someone has already signed up for both events, so the rehearsal slot has 1 open position, the show event has none.  If a volunteer selects and signs up for the rehearsal slot - we'll allow it and sign them up for both positions - over subscribing the show event.  If they try to select the show directly, it'll block them from signup.  

For part 2 - I'm thinking I can reduce the risk by warning the scheduling person if the pairs don't have the same # of slots when they are paired.  And most of our visualizations show if there's too many signups - I'll make sure of that.  I could also mail the people in charge of the event (staff leads, volunteer coordinator - same logic as signup notification) if this problem occurs.

**Comment by bethlakshmi** [comment]
Argh - another one - approval - if 1 event needs approval and the other doesn't, what do I do when someone volunteers?  Set to pending for the one that requires approval, and book for the one that is open?  And then if the volunteer is denied, remove from both?  .... I think that's the sanest?

**Comment by burlexpo** [comment]
The numbers should be the same.  Most of these shifts are a single volunteer.  The only place where I can see that might not be true is Stage Kittens, in which case I'd have the SM create shifts for "Core Kittens" (who need to be at rehearsals) and "Overflow Kittens" who don't.

If one requires approval, they both do.  Ideally, accepting someone for one will accept them for both.

**Comment by bethlakshmi** [comment]
Some notes on how things are actually working out here:
1 - It's a heck of a lot easier to give a user message "one or more of the slots in this volunteer opportunity are full, we are not accepting applications anymore", than to try to figure out how to create a message for "we signed you up for X but not for Y because Y was full, but X was available".  So I did the easy thing - if a Volunteer tries to sign up for a linked set of shifts, and 1 of the two shifts is full, then they won't be able to sign up for either one.  NOTE - this doesn't send a message to the staff at all (unless you tell me to).

2 - When an event is linked, there is no attempt to fix staffing retroactively.  Example:
- stage kitten show-time shift is created
- Can Do McKitten signs up for it
- stage kitten rehearsal time shift is created and linked to the stage kitten show-time shift is linked to it.
- Nothing happens to Can Do McKitten's schedule.  If the stage manager wants Can Do McKitten to be in both shifts, they will have to manually set Can Do that way, or ask them to withdraw and re-sign up the paired set of shifts.  

Second example:
- follow spot show-time and rehearsal time slots are created, and paired together. 
- Fancy McExamplePants signs up for the follow spot opportunity
- the follow spot shifts are separated.
- Fancy McExamplePants withdraws (or is removed) from the follow-spot show time shift.
- Fancy is still signed up for the rehearsal time shift - unless they also withdraw (or are manually removed) from it

I think these are all pretty rare edge cases.  Just limiting scope.

**Comment by bethlakshmi** [comment]
My previous notes on how this is going to work are wrong, so rewriting and will delete the old stuff.  Will probably put a final draft in the wiki when all this is done, cause it's nuanced:

1 - Volunteers have identical status on any change to their relationship to a linked event.  So if they are pending, waitlisted, rejected, removed, or officially volunteered for one, then so goes the other.  This applies even when 1 event requires approval and the other doesn't.

2 - The most restrictive business logic always wins - so if 1 event requires approval and the other doesn't - the volunteer is set to pending on BOTH events.  If 1 event is full and the other isn't - the volunteer can't sign up for *either* event.

3 - Linking 2 events does nothing to the current state of volunteers associated with those events (or any other role for that matter).  BUT - if you link 2 events, and then re-save a volunteer's status, then that status will automatically get updated on the linked event.

4 - Copying - when a linked event is copied, it's partner is also copied.  Always.  Even if the partner was NOT selected from a list of options, it's still copied.  There's some nuances due to the variations of bulk copy that we have:
    - if the copy operation is coming from copying a show w a bunch of volunteer opportunities - the linked event keeps it's relationship to the parent if it shares the parent with the other linked event.  If they have two different parents, the parent that is not the target of the copy operation doesn't get copied and the linked event gets copied, but the copy has no parent.  No events preserve their staff areas (that was always the case)
    - if this is a single occurrence copy (picking a volunteer event, and choosing to copy from the scheduler main page) - then anytime the two events share a parent - then the chosen parent will be used.  The location will be kept if it's still part of the current conference, the area will be reset with whatever was chosen for the chosen event.  That is definitely erratic, but doing otherwise makes this code weirder and it's already weird.
    - if the copy operation is done to a staff area, the same logic applies to the staff area relationship - if both sides of a linked event pair are in the chosed copied staff area, then the event copies are part of the newly copied area.  However, if the linked event does not share the area with it's linked partner then it gets copied, but has no staff area attached to it.  In a copy of staff areas, none of the copied events have parent events (that was always the case)

**Comment by bethlakshmi** [comment]
Going up on test server right now...

**Comment by bethlakshmi** [comment]
Not yet on test server... having problems deploying.  May or may not manage to debug tonight

**Comment by bethlakshmi** [comment]
OK, this time it worked.  Divio was sad yesterday or something... just verifed that paired events are up on test now.

**Comment by bethlakshmi** [comment]
It's LIVE!!
