### ISSUE TITLE
Feedback Mechanisms

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#466]
This will probably get broken out into multiple tickets but we need to work on accepting feedback from a variety of sources and making it available to the right people (and keep it from the wrong ones).  Off the top of my head
- **Class Evals** all of them should be accessible to the Conference Coordinator role; evals for individual classes get shared with the appropriate teachers.  How do we keep people who didn't take a given class from rating it? 
- **Volunteer Evals** At BHOF, we had someone abandon a security shift in the middle.  In our case, the staff lead might want to make a note somewhere (or not), flip a switch to keep that person from volunteering again, or if the person had a good reason for disappearing (Medical emergency, etc) not necessarily reporting it.  Also, it'd be be nice to be able to write GOOD things about people too!
- **Open Feedback From Attendees** I know that giving people a place to talk shit means that they will, but having some more formal attendee feedback mechanism might be useful -- also, better for the documentation chain if anything legal ever arises.

This might also be a Luna question.

**Comment by bethlakshmi** [comment]
Our class evals are available to the class coordinator:

Special -> Reports -> Class Evaluation Report - gets you here:
https://www.burlesque-expo.com/reports/review_volunteers/35

What I fear doesn't happen, is people finding the evals and filling them
out.  I wonder if we should do a little mail ping?  Also - it would
probably be good for Red to review the questions and make sure she likes
them... they are configurable, although I think it's in the /admin side.

Could definitely do a Volunteer review.  Right now, I don't think I have a
good data construct for that, but we could design it.

**Comment by bethlakshmi** [comment]
I'm going to start on a volunteer feedback mechanism while Luna works on the site prettification stuff.

I'm thinking about a data construct that is:
- per conference
- per volunteer
- per reviewer

So that - for example, John Bilotti can give 1 review, and Mike Bergman can give another.  And there's a new review for each conference.

The set of people eligible to be reviewed would be anyone who was signed up for any volunteer shift as a Volunteer -- we have other roles, though - should I include Stage Managers, Producers, etc? -- @burlexpo 

I'm thinking of making a display that shows:

- each volunteer for a given conference
- the schedule of shifts they were signed up for
- a list of every review per reviewer

So that everyone can see everyone else's review, and everyone can edit their own review.

Privilege to see/edit will be for ALL types of privilege in the system - we're still a really small leader group, and often we end up with volunteers floating between areas, so trying to confine reviews only to a person's area of leadership seems unreasonably constraining.

**Comment by bethlakshmi** [comment]
Volunteer Evals is ready to merge
Class Eval could still use a way to edit it in a more friendly way (but Red CAN edit it in the [admin](https://www.burlesque-expo.com/admin/scheduler/eventevalquestion/))

At what point should I close this ticket @burlexpo ?

**Comment by burlexpo** [comment]
I created two more separate tickets to deal with the other issues.
