### ISSUE TITLE
Put Media Release, Payment Info &c. on-line first

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#489]
For 2023 there are four forms we're going to want participants to sign-off on:

- Media Release (we're going to do our best to get people video; we get the rights to do what we want with the video)
- Directed Payment (what method do we use to pay people?)
- Code of Conduct
- Judging Conflict 

**However, not all participants get all forms**

I would like a way for participants to "sign" and fill out the information ahead of time.  Similar to tech info, they should get bugged about it and it should be displayed on their dashboard.

Front Desk staff should be able to see if an individual has filled out these forms but they do not need to see the details,; a simple "yes they have/no they haven't" is fine..  

If the participant has not, we should have a way for them to fill them out on the spot, whether that's 
- a paper version (not my favorite), 
- a terminal/.tablet available for the participant to fill out the info, or 
- a terminal/tablet and proper editing access for the Front Desk person to fill out the info on the participants behalf.

Last, we need a way for us to store the info in perpetuity and Scratch needs a good way to get s report of the payment methods.

**Comment by bethlakshmi** [comment]
I figure we want this place when Act applications close, since shortly after that, we're accepting acts, and act tech info bugging begins.  It's a lot easier to manage if form signing is in place at the same time as existing tech info, since we bug people all at once that way.

Tech thoughts:
- Electronic document signing seems to be it's own thing.  And not one I'd want to generate from the ground up.  I'll go look at tech and see what there may be in both library form and services.  The one I use most and trust is Docusign, which is definitely a monthly or annual payment:

The weird thing on them is they have:

- The Standard - and they have non-profit pricing!!  https://go.docusign.com/cobranded/4/impact/ - at < $20 per month
- API plans - that would integrate with our site - but that cost noticeably more - and the APIs aren't a direct win - they look very thoughtful and sensible, but I wonder if they really integrate well with our site.

I'll keep looking to see if I can find a cheap/free option.

--------

Restating the requirements in my terms, I think we need:

- a bit of logic for who gets what forms to sign - it's by segment of show, right?  Main event for competition gets the Judging Conflict form & no one else does, everyone gets Code of Conduct, etc... and that it limits it to max of 1 form per person (ie, if you are in 4 shows, you don't sign code of conduct 4 times).  Best to have this be configurable, not hard coded.
- a checker like the act tech checker (or part of it) that looks for the assigned forms to be signed and bugs the user.  This checker would be a level ABOVE the per-show act tech logic, since this is per-user.
- the presentation and signing of the form itself - electronically in some way.
- showing some sort of view to us, the staff on a per conference basis, showing who's signed their forms and what's outstanding.

It's a big feature.  About the same size as integrating with a new ticketing system.

**Comment by bethlakshmi** [comment]
@burlexpo - Should I start on this next?  It's big, but I did get some leads on open source document signing tools this year.

I can either:
- Hardest - look at APIs to doc signing systems.
- Easier - do something cheesy - like show the form content and have a checkbox that says "I agree", and then a form submit that records the agreement.
- Super easy - offer the forms on the Act Tech page and say "print this, sign and bring with you" - but that puts work back on the reg desk.

**Comment by bethlakshmi** [comment]
OK, we're on the medium grade, my idea for design is this - 
- have an alert on the recipient's dashboard page (same location as Act Tech Info, above or below it)
- It brings them to a page to sign all relevant legal stuff we need them to sign.  Each legal doc offers - a down load link that opens the PDF, a checkbox ("I read this") and a place to type their names.  And a submit button.  They do that, submit a valid form, and we consider it "done", keeping a record of who & what account signed what.  The page is block after block.
- When all forms are signed - alert disappears
- Staff (the admin?  Registration?) - can configure this through a special menu item.
- We had this system for how to give people what they should get at registration - badges, tickets, gift bags, etc. - I can repurpose that for this, the logic is the same - based on roles at this expo - so the logic can all be in one place.  The difference is that the "checklist item" is a file, and the presence of the "to be signed" file means it becomes part of this work flow.  I'll want to maek a configuration page where the staff can upload a file, and set the choices for who has to sign it.  Based on us talking, I think it's really just based on role - teachers, performers, volunteers, etc.  In the long term, I'd like to build out this area, since it's obscure right now, and I'm the only one who can really do it (I can't even figure out how to explain it to a normal person).

Questions:
- do we show them previously signed forms?   Can they "unsign"?
- do they get a persistent link to what they signed on their home screen?   Or another view attached to their account, maybe accessible through the menus?  Seems like they should definitely be able to get access to what they signed, but that it should be in an out of the way place.

**Comment by burlexpo** [comment]
do we show them previously signed forms? **YES**
Can they "unsign"? **FUCK NO**
do they get a persistent link to what they signed on their home screen? Or another view attached to their account, maybe accessible through the menus? Seems like they should definitely be able to get access to what they signed, but that it should be in an out of the way place. **SEEMS LIKE A BUTTON IN THE "SCRATCH'S STUFF" COLUMN WOULD BE THE RIGHT PLACE.  SAME PLACE I WOULD GO TO VIEW MY HISTORY OF BIDS.**

**Comment by bethlakshmi** [comment]
Good with all answers.
Note to self - the reg desk needs a few extra things:
1 - add SIGN THESE FORMS (and what forms) to the welcome letter of everyone who didn't sign their forms.  And a "all forms signed, thanks!" the good doo-bees so Marek knows who needs to do more work.
2 - make a reg desk friendly way for people to sign forms.  The vibe is - something fast that doesn't clog reg desk, but they don't get their badges and stuff until we get signed forms, so it has to happen and be verifiable by Market & team.
3 - (bonus?) we want to hound them with an email  & template just like we do act tech info deliquents.

**Comment by bethlakshmi** [comment]
OK, first thread done - how's this look?

<img width="572" alt="Screenshot 2024-01-30 at 9 02 26 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/84e5c6e0-0d85-4690-b74a-5d31166d3430">

**Comment by burlexpo** [comment]
Looks good!

**Comment by bethlakshmi** [comment]
OK, got the sign form looking pretty, now to see if it works.
The Read Form button opens up a new tab with the form.

... do we like "Name signed" as the label?  It's easy to change.

<img width="1156" alt="Screenshot 2024-02-03 at 11 46 33 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/fb396dd4-0ce9-4a5c-abf0-e59845399886">

**Comment by bethlakshmi** [comment]
Welcome letter update!

How's this look?  Reused our styling for danger alerts to make it really obvious (I hope).  And now the big blocks of text are customizeable.

<img width="1664" alt="Screenshot 2024-02-05 at 8 50 13 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/f98811c4-5874-44dd-a783-d4be86f830a7">

**Comment by burlexpo** [comment]
Looks good.  What exactly is customizable on the "Package Checklist"? Just that first line?

**Comment by bethlakshmi** [comment]
Nothing is customizeable about the Package Checklist.  Did you want the header to be customizeable?  

Only the two places I have arrows are customizeable right now.

**Comment by bethlakshmi** [comment]
Here's another question...  I'm about to build an email annoy-o-gram for people who haven't signed their forms.  Much like the act tech info.  Do we want the frequency of that to always be the same as act tech info (in which case, I'll glob the two together into a single command)?  Or would we want a different frequency for the signing form impaired?

**Comment by burlexpo** [comment]
> Nothing is customizeable about the Package Checklist. Did you want the header to be customizeable?

Sorry.  Too early.  I was notcing that some things on the "Package List" may not be accurate, that's all.

**Comment by burlexpo** [comment]
> Do we want the frequency of that to always be the same as act tech info (in which case, I'll glob the two together into a single command)? Or would we want a different frequency for the signing form impaired?

I'd like the same period but a different frequency, he said in mathnerd.  That is, if Act Tech annoy-grams go out weekly on Mondays, I'd like the "Sign Your Damn Forms" reminder to go out weekly on Wednesdays

**Comment by bethlakshmi** [comment]
w/respect to the actual checklist items - that is customizeable... just not easy since I've always done it myself.

This is a better view of the current logic: https://www.burlesque-expo.com/ticketing/checklist - but anything here can be tweaked, just let me know.

> I'd like the same period but a different frequency, he said in mathnerd. That is, if Act Tech annoy-grams go out weekly on Mondays, I'd like the "Sign Your Damn Forms" reminder to go out weekly on Wednesdays

Nerd-a-stay - the math nerd in me greets the math nerd in you.

OK you got it, separate commands.

**Comment by burlexpo** [comment]
> This is a better view of the current logic

The thing I was looking at was "Performer Ribbon - green with white stripe" and I though "Are they? How would someone change that if they're pink this year?"

**Comment by bethlakshmi** [comment]
Yeah - that's an editable checklist item.  If we're out of those, I can easily change it.  I told Marek (and it says in my docs) to ask me if he needs a change, cause I never wrote nice screens for this.

My plan was to start making something nice for this edge of the system as I do this ticket - but to limit the scope to setting up the PDFs and who "signs" them, and then worry about the rest later.

**Comment by bethlakshmi** [comment]
OK, the first release of this feature is live on production.

If you have forms you want signed, mail them to me, and I can put them up through Admin.
And what day do you want to send the annoy-o-gram?

In the meantime - I'm proceeding with the rest of the features.

How does this look for a view of the forms the user has signed?

<img width="1352" alt="Screenshot 2024-02-13 at 10 09 32 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/830e641a-2804-4a6a-80b5-b020e63bb349">

The file they signed shows up in a separate tab.
I'll also clean up the date, as this is not our standard date format.

**Comment by burlexpo** [comment]
Report looks good to me.  You should probably be asking @marekrivero how he feels about it ;-)

**Comment by burlexpo** [comment]
[2024 General Recording Release.pdf](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/files/14269156/2024.General.Recording.Release.pdf)
[2024 Payment Direction.pdf](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/files/14269157/2024.Payment.Direction.pdf)

Here is the Payment Information Form and the Media Release.

**Comment by marekrivero** [comment]
The data looks good. Easy to read and track if I need to look it up when
checking someone in.

**Comment by bethlakshmi** [comment]
This was actually the per user view not the reg desk view

**Comment by marekrivero** [comment]
Where should I look to see reg desk view?

**Comment by bethlakshmi** [comment]
It’s not ready yet

**Comment by bethlakshmi** [comment]
<img width="543" alt="Screenshot 2024-02-14 at 7 45 22 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/bb448113-97f8-406f-a7b7-54a57bdb2eaa">

Not bugging either of you because it's intermission at the show on Valentine's day.

But how's this for the place that the user uses to navigate to their signature list page?

The order of stuff on this column of the home page is:
- title
- switch between historic/current bid view
- Alert about Act Tech info (if relevant)
- Alert about Unsigned forms (if relevant)
- Act bids
- Class bids
- Costume Bids (if relevant)
- Vendor bids (if relevant)
- Link to view signatures (if relevant)
- Reviews the reviewer should review (if relevant)

All those "if relevants" are conditional.  So, for example, if the user hasn't signed anything, they won't get a box.

Is that a good order of stuff?

Som

**Comment by bethlakshmi** [comment]
@marekrivero and @burlexpo - how's this for the registration management view?

<img width="1153" alt="Screenshot 2024-02-14 at 11 18 29 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/04bb1a11-8608-45a3-b1d7-c34422b14921">

On the top row - Betty signed all her forms and it shows the list of what she signed this expo.  Her row is white, cause she's all set.

Scratch, however, signed only 1 of the two forms - so it shows what forms he didn't sign, and puts a big SIGN HERE button.  This will take you to a form that he can sign if we hand him a tablet and ask him to enter the data.  That view will be a lot like the view for signing one's own forms earlier on this ticket (https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/issues/489) but it'll be accessible through a Registration privileged user (ie, Marek... or Betty and Scratch cause we're just everything).

**Comment by bethlakshmi** [comment]
@burlexpo - I just read the forms you gave me ... and I'm confused.  The forms have places where the user has to input information.  In particular, the Payment Direction form is useless if they don't check boxes and give us account information.

All the user can do with what I've written is put text in 1 box.  They can't upload a file, they can't check off anything.  

How are these forms supposed to work?

**Comment by bethlakshmi** [comment]
OK, I'm finding some form builder things that might work for the payment method form.  Apparently it's a "Form builder" that we're looking for.  Since a big part of Django is "forms" there's a whole lot of other form tools out there that are not what we want. 

Source : https://djangopackages.org/grids/g/form-builder/

- https://github.com/UniversitaDellaCalabria/django-form-builder?tab=readme-ov-file
- https://github.com/feincms/form-designer?tab=readme-ov-file
- https://django-fobi.readthedocs.io/en/latest/#key-concepts

None of these have working demos, so I'll have to install them to see how they actually work.  I think the last one is possibly the best - integrates with Django CMS if we ever want that, seems to have a lot of features.  I think what we want the most is:
- form fields that include text boxes, radio button, checkboxes - with a way to combine validation - i.e. if the user picks "pay me by Venmo to Venmo id --insert venmo id--"  then if this option is selected, the Venmo id MUST be provided.  If they don't select venmo, the id is not required.  That combined validation rule is not out-of-the-box Django - it's easy enough to code, but it would also need to be something the tool configures.
- form submission can be attached to a user account - many of these provide RECAPTCHA protection so you can do anonymous surveys.  We actually know we're working with logged in users, so we just want to connect the form to the user.  
- a way to make a view that registration sees
- a way to let registration create the form on the user's behalf.

**Comment by bethlakshmi** [comment]
Given the long run of this ticket, I'm closing it, as the original work described is done with the PR I just merged.  Will write another ticket describing where we went with this feature in our latest research
