### ISSUE TITLE
[Website] Nav bar design

### ISSUE THREAD

**Issue by carynaudenried** [bethlakshmi/gbe-divio-djangocms-python2.7#492]
**Design needs**
- New look and feel for navigation UI; include existing logo
- Include placement for log in/register button
- Anchor navigation to top of page

**Comment by carynaudenried** [comment]
@burlexpo Moving this convo to Github.... I'd like to get your feedback on this nav design before I get further.

The issue I'm running into with the existing logo is that it doesn't translate well to small spaces like the nav. The circle makes it hard to scale down to a short space, and the smaller letters become unreadable.
![Screen Shot 2023-07-03 at 1 06 54 PM](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/4ffe9b44-6acd-4ef5-98e9-9904647eec30)

I'm proposing we create a "small space" version of the circle logo for use in the nav, so that you always have a logo present on the page. Here's a mockup of what that could look like. I did my best to match the fonts, but even better if you can get the names of the fonts or the original creation file for that logo so I can use the exact match. What do you think about this approach?
![Screen Shot 2023-07-03 at 1 05 30 PM](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/56ef83dd-3852-4b56-82e2-861615e1edf3)

**Comment by carynaudenried** [comment]
@burlexpo following up here as I catch up! What do you think of the design proposal I posted above using an alternate version of the circle logo for the nav bar?

**Comment by burlexpo** [comment]
@carynaudenried Thanks for following up! I;m fine with the alternative version of the logo.  I wouldn't even worry about the fonts; since the original had to be sort of mashed to get it into the circle, I think yours is close enough.  I do have a small, rectangular version I used for the pens.  
![logo - horizontal - 300 dpi](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/5369404/a9fcb399-603c-41e1-9c87-3e5563b12fe7)
![logo - horizontal 141x114](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/5369404/90aa475f-ed70-478a-a131-ce0ce5ee7e88)
![logo - horizontal](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/5369404/738ae437-ed4e-4618-b854-7fccd51e010d)

**Comment by carynaudenried** [comment]
@burlexpo great, thanks!

Here's what I'm thinking for the full styling of the nav, then. These are ready to be worked on (tagging in @bethlakshmi to take a look )I'm also attaching exports of the smaller logo I recreated - I think it's good to keep the fonts somewhat similar to the original circle logo. 

Let me know if anything doesn't make sense. Here's a link to the Figma if that's easier to inspect the details: https://www.figma.com/file/Pk1Of5sOwOdrjftUqiegaL/BurlExpo-Site?type=design&node-id=409-131&mode=design&t=2PI84jeuqY7AKQEV-4
![GBE Nav Designs](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/935fea98-4b74-40c4-adaf-06252b22fe51)
![GBE Nav Specs](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/5fbc59e9-2f32-4b71-b8a5-49177c9c201c)

Logo exports (1x and 2x - do we still use 1x assets anymore?)
![GBE_Nav_Logo](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/febf2b28-d315-4c2c-8108-d9291cf0ec88)
<img width="105" alt="GBE_Nav_Logo@2x" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/4b4dd84a-c412-4612-ab92-cb65bcd0ada9">

**Comment by burlexpo** [comment]
Visually, I like the fonts, organization, and layout a lot.  Is this the color scheme you're leaning towards? It seems a little muted for "burlesque", but I don't see colors that well.

The content of the menus, on the other hand, is kind of chaos.  They grew sort of organically.  I would love your help @carynaudenried creating some organization that made sense

**Comment by bethlakshmi** [comment]
comments:

- I am not sure I can get the hamburger to X conversion given the tool I use (Bootstrap) for this... I can fool with it, just not sure.  
- also not sure if I can move the carots from side arrow to down arrow when the menu gets expanded.  Should be easier than the hamburger to X, just not sure yet.
- So far, can do the rest.  I'll start on it soon, I think most of it is not code changes - maybe only the font is a code change.

I'll probably be a bit slow - I'm finishing up a merge users function that is dragging on (but nearly done) and having a whole lot of family life right now

**Comment by bethlakshmi** [comment]
Are we good on colors?  I'm going to start on setting up a complete copy on the test site:

https://burlesque-expo-stage.us.aldryn.io/main/

Where I already have the code to change up the layout.  So I'm going to get anal retentive now on height, color, font etc.

**Comment by bethlakshmi** [comment]
@carynaudenried and @burlexpo - OK, I just did the top level of menus.  The settings in figma are partially transparent, and on top of the red curtain background the difference between hover and not-hover seems a little subtle to me.

What do we think?

https://burlesque-expo-stage.us.aldryn.io/themes/style_edit/1

**Comment by burlexpo** [comment]
@bethlakshmi not sure what you mean by "top level".  In the attached is it "Events" "I Want To..." "Conference" etc? Because if so there is no perceptible difference (to me) on hover vs non-hover.  The menu items seem clearly indicated on hover, though (see bleow)
![Screenshot 2023-08-28 at 12 09 28 PM](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/5369404/8dc298a3-7249-45a1-9551-e27865c39250)

**Comment by bethlakshmi** [comment]
Yes, that is what I mean.  The stuff in the black bar at the top.

There is, believe it or not, a slight distinction in the hover. It is very, very slight.  If you logout (to get rid of the django cms menu) and then scroll around so that the light color page part is underneath the menu, then the hover difference is a lot clearer.

The way the design calls for it - the menu bar background color, and the hover background color are both slightly transparent.  So on the red background, there's a lot less distinction between these two colors than on a light background.  And the design in Figma is using a medium gray background, because we haven't picked background color yet.

... so all that is the long way round to:
- do we want a distinct hover color?
- if we do - do we change the menu/hover color or the background color?

FYI - there's more work to do on the LOGIN button - I got it close, but there's more cleanup on hover text color (currently a sickly green color) and probably other aspects there.  That was where I stopped for the moment.  It used to be a button, so de-button-ifying was a process.

**Comment by bethlakshmi** [comment]
OK - FYI - I think I have this all done:
- all top menu items - including login - work to spec, on all states (active, focus/hover, regular)
- mobile view and desktop view for all top level looks good
- logo is in place
- hamburger to X transition works

What's left:
- sub-level menu items
- login panel
- buttons on top level menu
- fix bug for "active" state - the bug is that the tracking on what's active only runs 1 level deep, it doesn't handle recursion properly (never did) - I figure this might be optional, and if it takes a while, I won't do it.

All changes are up on the staging site.

**Comment by bethlakshmi** [comment]
OK!  I think I have it all!  Also went through the detailed specs on the right of the figma and I put a few comments in there on where I couldn't get it to work exactly to spec.

@carynaudenried and @burlexpo  - can you go over it closely?  There's a lot of little fiddly details to these menus.  Stuff particularly to look at:
- spacing both for desktop and mobile - expanding and contracting your browser width will show the variations
- hover/focus - when the mouse is over something (hover) or when it was just clicked (focus)
- active - a menu item that is actively shown on screen - changes the look of the menu
- logged in/logged out - the login panel only shows up if you are logged out

Also - I kept the editor up to date with stuff I added so - https://burlesque-expo-stage.us.aldryn.io/themes/style_edit/1 - will show demos of the various menu items in the "Menus" section.  I did not do any of the login stuff there - it's in the "Everything Else" section (no pretty demo yet).

I'll work on the active bug (that activity only shows up 1 level deep, not recursively) but the only real blocker to publishing now is a second/third set of eyes.

**Comment by burlexpo** [comment]
I tested things both logged in and logged out

**Thoughts/notes:**

- Hovering over the Menu header ("Events", "Conference" etc) is a very _subtle_ change to my eyes.
- Hovering over the menu header doesn't reveal the menu.  I have to click on it.
- Menu headers are decorated to show whcih section I'm in
- When i click the active menu header to see the dropdown menu items, the page I am on is highlighted.
- The highlight color for the page I'm on seems to be the same as the hover color.
- Clicking the logo doesn't seem to do anything.  Is it supposed to?
- Clicking the header image does take me to the Home page
- The three buttons seem to work fine
- Shrinking the screen converts from "menu" to "hamburger" just fine
- Login panel works as expected

**Comment by bethlakshmi** [comment]
Agree on:
- **Hovering over the Menu header ("Events", "Conference" etc) is a very subtle change to my eyes**. - yeah, I'm not sure how to tweak this - could do either a lighter background color so the difference is clearer, or we could do a header with different transparency.  
For comparison - here's the header on the curtains, dark red background:

<img width="586" alt="Screenshot 2023-09-01 at 11 27 12 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/3b0b8e11-997a-4496-ac26-3f78ba51d743">

and here it is on the light panel color:

<img width="455" alt="Screenshot 2023-09-01 at 11 27 29 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/c78e7161-73ec-4843-9ee7-8f9ceb920a8c">

.... way clearer.

- **The highlight color for the page I'm on seems to be the same as the hover color.**
Yep. That's my bad.  Just fixed it.  I *think* I've got it aligned with the design, but check me on this:
  - menu at normal = 65% transparent gray.
  - menu that's active (current page is in this menu) = same (65% transparent) and underlined.
  - menu that you hover over (but did not click) = darker (85% transparent), and NOT underlined
  - menu that you clicked and opened = darker (85% transparent, just like hover) AND underlined
That last one was creativity on my part, perhaps.  It came about because when in mobile view, the active menu header blends into it's subitems quite a bit  but with the underline, it's clear it's the header above the other stuff.

- **Clicking the logo doesn't seem to do anything. Is it supposed to?**
the spec doesn't say anything - but it could.  A common thing would be take the user back to the home page?


Other thoughts:

- Hovering over the menu header doesn't reveal the menu. I have to click on it.

Yes, that's how it works now, and that's what bootstrap gives us.  I actually really dislike hover menu opening - [this article](https://wecreate.digital/blog/menu-clicks-vs-hover/#:~:text=Due%20to%20'hover%20tunnels'%2C,greater%20flexibility%20in%20mouse%20movements.) includes my reasons and more.  For me, the big one is that I'm really bad at hover menus - they always leave me swearing.  But the fact that mobile devices don't have mice so don't have hover is the killer reason, IMO.

- buttons - 
FYI, also - I was able to create this:

<img width="1156" alt="Screenshot 2023-09-01 at 11 58 18 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/2e3cf2a2-4c15-4f34-b4d0-05fbfbd38c95">

<img width="884" alt="Screenshot 2023-09-01 at 12 02 30 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/0a7a855a-3752-4353-9eea-a34516b1c299">

by sizing my window to be smaller but not so small that it flipped into mobile view with the hamburger.  I'm not sure there's much I can do about this - but it's a thing to be aware of.  Basically - too many menu items + too many buttons = weird scrunchy buttons.  Also (second image, see green arrow) - it means that any time a menu item is getting the darker background color, the sizing of the menu item box, is smaller than the now taller header - because of the stacked up buttons.  

I'm definitely open to how to smooth this a bit... should I put some spacing between the buttons top & bottom?  I could try to make the height of the menu items auto-resize to always be 100% of the menu height...?  or we could make sure that this is a rarity.  BTW - the magic number is 992 pixels.  This is what bootstrap uses as the cutover between a desktop style menu vs. the hamburger menu.  So that's the place to test when we're deciding what the menus should be.

**Comment by burlexpo** [comment]
**Hover Header color** instead of changing the opacity of the background, could we change the color of the font? From something like white (unhovered) to yellow (hovered)? @carynaudenried what do you think?

**Logo Click** yes, have it take you back to the main page

**Comment by bethlakshmi** [comment]
logo click is done.

I have a new theme ready on the main site called "2023 Menu on Top" which I'll cut over to when we are ready to install the new menu.  It will need some manual changes at the same time, since I changed some CSS classes around, but I think I've minimized it enough to make it easy to replicate what we have on test on the live site pretty fast (less than an hour)

Now just waiting the color change question.

**Comment by bethlakshmi** [comment]
Researched the "active" bug - I thought it couldn't do multi-level depth on what page is currently active.  That's not true, it works fine.

What doesn't work is any case where I'm using GET attributes as a selector.  For example

This works fine:  https://burlesque-expo-stage.us.aldryn.io/scheduling/view_list/Special/

This doesn't: https://burlesque-expo-stage.us.aldryn.io/calendar/General?day=05-05-2023

I don't have a way to fix this - the decision on what an ancestor is gets done in Django CMS.  But I could change how we map URLs to avoid using GET requests.  For example, the not-working URL for a calendar, could instead use the syntax:

https://burlesque-expo-stage.us.aldryn.io/calendar/General/**_<day in MM-DD-YYYY format>_**

And the active logic would work just fine.  

Do we think this matters?  if so, I'll do it under a separate ticket.

**Comment by bethlakshmi** [comment]
Here's another one on the "does this matter?" - mostly @burlexpo  - cause it will be his pain in the ass.

The new design uses Montserrat in place of Vast Shadow.
But there's no automatic way to port all the places where our context references Vast Shadow.  So, as a result - headers like "Code of Conduct" on the [main page](https://burlesque-expo-stage.us.aldryn.io/main/) look sort of sad.

I can do any of the following:
1 - pull out Vast Shadow completely (currently what staging shows), and leave it to Scratch to update all headers as he sees fit.  Montserrat is available in the CK Editor, the way Vast Shadow used to be, he just has to manually update it all.
2 - leave the Vast Shadow font in the list of links we reference in our base html - that will mean that any CMS text properly displays with the Vast Shadow font, but that no new text can be made with it, because I have pulled it as an option from our editor.
3 - leave Vast shadow in the editor, too, so that we can continue to use it.

I lean towards 2 with a later ticket to pull it completely after we've reviewed and updated the text... thoughts?

**Comment by burlexpo** [comment]
What I would love instead of "Vast Shadow" being some sort of separate thing, is just to be able to set the styles for H1-H6 and if I want one of them to use a specific font in every instance, to have access to those fonts.

**Comment by burlexpo** [comment]
**Active bug** it should be consistent.  If we're showing people what page they are currently on, we should do it all the time or none of the time.

**Comment by bethlakshmi** [comment]
Active bug - #505 - OK, working on it.  Looks pretty contained.

On the setting of fonts in the editor in Django CMS - I think we need to talk, because I believe that's how it works right now.  Because "Vast Shadow" was set as an explicit font, we have problems.  I can set a font on the h1-h16 styles and then when you use those styles, that'll be what you get.  But what font do you want on what style?  Do you want all of them to just use Montserrat?

**Comment by burlexpo** [comment]
This may be a @carynaudenried question, but I'm pretty sure I don't want all of them to be Montserrat; it's a pretty boring font.  I'm thinking "Creepster" or "Poiret One", for the header fonts, depending on which vibe we're going for

**Comment by carynaudenried** [comment]
Looking over everything now! Sorry for the delay, this has been an incredibly busy month.

Re: fonts -- we don't have to use Monserrat for the header styles -- I was thinking that'd be good for nav and smaller text since it's very readable. I'm open to any font, particularly "Limelight" since it's a bit more versatile and has both caps and lowercase. https://fonts.google.com/specimen/Limelight?query=limelight

**Comment by carynaudenried** [comment]
First off, Betty, this looks great! 

Weighing in on the comments above:

**- Hovering over the Menu header ("Events", "Conference" etc) is a very subtle change to my eyes.** 
Yep, this will look much more subtle over a dark background like we have now. I like a somewhat subtle hover state but since we'll probably have a dark background for the site going forward, I'm good to go with Scratch's suggestion of a yellow color for the text instead of the darker opacity background on hover. Something like this? Or maybe we could keep the darker background and also add the yellow color for a bit more focus (color is #FDD76A)
<img width="680" alt="Screenshot 2023-09-09 at 4 21 44 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/efd30ea7-74fe-4bbc-b68a-c2c751b3e040">

**Hovering over the menu header doesn't reveal the menu. I have to click on it.**
Agreed with Betty on this one, hover menus aren't a great UX pattern as they can be difficult to navigate, esp with our flyouts in the menus. They're also less accessible for visually impaired.

**Clicking on the Logo**
Yep, that should go to the home page -- sorry for not calling that out.

**The highlight color for the page I'm on seems to be the same as the hover color.
Yep. That's my bad. Just fixed it. I think I've got it aligned with the design, but check me on this:

menu at normal = 65% transparent gray.
menu that's active (current page is in this menu) = same (65% transparent) and underlined.
menu that you hover over (but did not click) = darker (85% transparent), and NOT underlined
menu that you clicked and opened = darker (85% transparent, just like hover) AND underlined
That last one was creativity on my part, perhaps. It came about because when in mobile view, the active menu header blends into it's subitems quite a bit but with the underline, it's clear it's the header above the other stuff.**

I see what you solved there -- on mobile it does seem helpful to have more focus on the menu you clicked and opened. I'm good to go with keeping the underline there as well as the dark background/yellow color text we're using for the new hover state for when you've clicked and opened a nav menu.

**Buttons at 992 pixels**
Yeah, for now we can hope this is mostly a rarity -- My thoughts on how to handle this is we have two options:

- Remove the buttons when your browser is between 992 pixels and however wide it is when it cuts over to mobile view
- Add a bit of padding to the buttons top and bottom so they look more spaced out when they do this (maybe 5px)

I'd say maybe let's go for the second option, and we can think about hiding them later if it feels like they're getting in the way. Tablets are still used but probably not as much as laptop sizes or mobile these days.

-----

**Other comments**

Super nitpicky, but I noticed a couple things on the Login menu:

- The font weight is pretty light on the text entry, is it possible to change to Montserrat Regular?
- It looks like the letter-spacing is applied on a couple of the pieces of text in here where it shouldn't -- the "Forgot password?" and "New here? Join Us" links.
<img width="390" alt="Screenshot 2023-09-09 at 4 37 01 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/9b403569-85e9-477c-8915-048ddee3ad66">

**Comment by bethlakshmi** [comment]
- hover color - love it, done!
- homepage on logo click - done!
- Buttons at 992 pixels - I like that answer...  done!  definitely option 2 is better looking:

<img width="259" alt="Screenshot 2023-09-10 at 12 20 45 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/b6319d29-4833-4cc9-9381-f461631017a9">
<img width="308" alt="Screenshot 2023-09-10 at 12 20 56 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/d905b69c-8a5c-4bff-be7c-8d88a4caeee5">

I used margin of 4 px top/bottom, only because that's the easy way with bootstrap, and it seemed close enough.  Let me kow @carynaudenried if that's not good enough.

@burlexpo - Fyi, this introduces a bit of fussiness if you ever want to change the buttons.  I did them with Django CMS, because that's how you built these buttons in the first place.  To make them look nice, I added an attribute for "class" with a value of "m-1" - which is bootstrap-ese for adding the smallest possible margin to the button.  If you want to add buttons, I suggest copying one that's there, not DYI-ing it, cause this attribute value is really hidden... -- it's nested at the bottom of the options:

<img width="1691" alt="Screenshot 2023-09-10 at 12 20 12 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/0d533109-c939-4780-a966-eec842d67803">

Other comments - fixed fonts on login menu.


Any others?

**Comment by bethlakshmi** [comment]
I think the only question I still have is about Vast Shadow and whether to keep including it?  or to include any other jazzy fonts for use in page text?

**Comment by carynaudenried** [comment]
@bethlakshmi nice! the 4px looks good, I think option 2 is fine as well.

I'm looking at the staging site and am not seeing any changes to the login menu, is this where I should be looking? https://burlesque-expo-stage.us.aldryn.io/main/

Re: Vast Shadow -- I think if we introduce Limelight as our display font, and Montserrat as our text font, that's enough (and if we want to do something fancier with image headers for certain areas, we're not limited to those two), so my vote is to remove Vast Shadow. However if it's easier to keep it in for the older content, that's fine, but I could see how removing it might make things load faster. Kind of a judgement call for you both.

**Comment by bethlakshmi** [comment]
OK, just put up the update:
- headers are set with these font styles
- got the CK Editor used in Django CMS to include these fonts, so that:
    - if you pick a header - you just get the headers with the right fonts
    - you can also set this font as a <font> tag inside anything, with any font size
- found a few other places were I had just replaced Vast Shadow with Montserrat, where it makes more sense to use Limelight or Bebas Neue - so fixed CSS in those places.
- set up Tiny MCE (what we use when editing text inside of GBE code - like the event descriptions) - so that our Admin editing also includes all 3 new fonts.  If you just use headers - you'll get the right text (Limelight or Bebas Neue) but the font selection lets you pull it in when you don't want to use the headers that way.

I think that's everything?  

If we wanted to do more with the text in the main area of the page, I suggest we do another ticket.

**Comment by carynaudenried** [comment]
Sounds good. I think we can close this one out! (Or whatever is best on Github, I'm not sure how you want to manage these threads!)

**Comment by burlexpo** [comment]
Yup -- we mark the issue as closed.  We can always re-open it if necessary ;-)
