### ISSUE TITLE
reminder - update communication stuff on bid submissions

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#517]
Was just working on #462 and noticed:

- Act Intro text is very dated to GBE 2023 - https://burlesque-expo-stage.us.aldryn.io/act/create (shown on staging, because live has bids turned off) - update it here:  https://burlesque-expo.us.aldryn.io/admin/gbe/usermessage/81/change/?_changelist_filters=view%3DMakeActView
- The shows to be interested in are last year's shows:

<img width="1115" alt="Screenshot 2023-09-17 at 10 40 51 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/59ed30d3-5814-4f2b-8dff-2f6c76877323">

This one is a code change - give me the show names and the small text descriptions and I'll put it in there and push an update.
(I could also do a ticket that makes this dynamic -- but that won't fit before our deadline)

- this one also has dates in it - https://burlesque-expo.us.aldryn.io/admin/gbe/usermessage/16/change/?_changelist_filters=view%3DMakeActView - the message when they successfully submit, tells them when they will get a response from us.

In terms of the other types of bidding - they all deserve a look, but the bid instructions on the others all look more generic:

https://burlesque-expo.us.aldryn.io/admin/gbe/usermessage/?code=BID_INSTRUCTIONS

Same for submit success:

https://burlesque-expo.us.aldryn.io/admin/gbe/usermessage/?code=SUBMIT_SUCCESS

**Comment by burlexpo** [comment]
Here's the complete list of shows people can express an interest in

Thursday, April 25 @ 8pm <B>Half-o-Ween!</B> Whatever happened to the <I>Transylvania Twist</I>? It's now the BurlExpo's salute to spooky season! We'll take anything that goes bump in the night &mdash; as long as they're your best!

Thursday, April 25 @ 10pm</I> <B>Opening Night Party</B> We're taking over <a href=https://www.deacongiles.com/the-speakeasy-lab>The Speakeasy Lab at Deacon Giles</a>. Something really special happens when performers are performing for other performers.</LI>

<LI><I>Friday, April 26 @ 10pm</I> <B>The Burlesk Bordello</B>  21+! This intimate, late-night cabaret lets you get up close and personal with the audience.  Bring us your sexiest, kinkiest, steamiest acts!</LI>

<LI><I>Saturday, April 27, 7:30PM</I> <B>The Main Event (not in competition):</b> An amazing opportunity for newer performers or those who want to be seen on the big stage without the pressure of competition!</LI>

<LI><I>Saturday, May 6, 9PM</I> <B>The Main Event (in competition):</b> Our big event gets even bigger this year! Bring us your <em>best</em> act to compete for titles, prizes, and cash!</UL>

**Comment by bethlakshmi** [comment]
Boom!
<img width="828" alt="Screenshot 2023-09-27 at 11 06 44 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/08215df7-ba2f-4780-b897-bf0d7c81100b">

setting up PR now.

**Comment by bethlakshmi** [comment]
deployed!
