### ISSUE TITLE
Act Submission Acknowledgement email?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#542]
When someone successfully submits an act, the Act Review committee is notified.  Do we send a "receipt" to the submitter? If not, can we? If so, people are not receiving them...

**Comment by bethlakshmi** [comment]
We do not send them an email when they submit.  We do send them email when they are accepted, rejected, etc.

I think we decided that since we DO give feedback as a message at the top of the next page, and in their dashboard we could spare them the email.

So this is a new thing -- scope clarification:
- send an email to the submitter when they submit any bid?  Or just acts? (one is as easy as the other)
- email format will be customizeable by the coordinator on a per-bid-type basis (act, class, costume, vendor) - NOT per show, because we haven't cast them into a show yet.

Not totally easy, it'll take me a few hours, but certainly not hard.

**Comment by burlexpo** [comment]
Yes, a customisable email, one per bid.  That would be great.  Thanks.
