### ISSUE TITLE
Creating Comp Ticket = Server 500

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#562]
If I go to

https://www.burlesque-expo.com/ticketing/transaction/create?next=/act/reviewlist?changed_id=1176

and click the Comp button (to give someone an acr fee 'credit', not to create the entire act), I get a Server 500 error.

More info --

If I leave the page (say, by going back to my dashboard), I can come back and create a comp ticket, but I can't create two in a row (for different people).

**Comment by bethlakshmi** [comment]
woah.  Nice.  By nice I mean "how wild, and I can't believe I didn't test that."

**Comment by burlexpo** [comment]
You don't have that problem when doing a comp from https://www.burlesque-expo.com/ticketing/transactions because the workflow is slightly different.  From the Transaction page, I go and do the comp, and when it is successful I am returned to the Transaction page.  When I do it from Acts, I remain on the Comp page.

**Comment by bethlakshmi** [comment]
so dumb.  Collision of 2 problems.
1 - the link to "Send a Comp" on the act review page included the redirect url as the FULL url - including the get request (changed_id=whatever) which appears on the second time you tried to comp someone.  That changed id is the successful comping of the first try.
2 - the redirect on the transaction creation did not scrub that stuff - so what it created was a redirect that looked like:

[https:://](http://0.0.0.0:8000/act/reviewlist?**changed_id**=1191?**changed_id**=1176)

Not great - since at that point it's a malformed URL, and which changed_id should the system actually parse?  

Fixed both problems 1 and 2. 

retesting now, and will create a few test cases.

In the meantime, if you are trying comp multiple folks in a session, make sure that if you are on the create transactions page:

http://0.0.0.0:8000/ticketing/transaction/create

And it has a changed_id on it, you pull off that changed id before submitting
Also - the comp actually succeeds, the user IS comped, so if you do get the error, you don't need to comp them a second time.
