### ISSUE TITLE
Recover a page?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#58]
I did a bunch of work on one of our pages (_...Book A Room_) and then deleted it by mistake.  There's supposed to be something called Django CMS History which will allow me to recover it, but I can't figure out how to access it.  It's not a disaster, but I spent about 1.5 hours creating the page, so if there's a way to recover it rather than me doing it all again, that would be great.

**Comment by bethlakshmi** [comment]
Remember how I said that I wasn't keeping our version history in the converted site?
.... yeah....

The only thing I can think to do is spelunk into our database backups and see if I could do a recovery from there.  I'd have to do something somewhat manual, because I'm afraid of loosing other user data if I just reload the old DB, I'll erase it.

**Comment by bethlakshmi** [comment]
BTW - there's some history of why this isn't part of our Django CMS written here:
https://github.com/divio/djangocms-history

They removed it in the time between the version that was on web factional, and the version that we have on Divio.  I didn't fight to re-integrate it, because it actually caused me a certain number of problems - keeping all the old versions made it very hard to remove old plugins that we no longer wished/needed to use, but that had been used in an old version somewhere.  The more plugins we have, the slower certain functionality gets (mostly in the Django CMS editing side)... so it did cause user frustration.

And the time or two you needed me to recover something, I spent several hours fighting with it... so it seemed to do more harm than good.

**Comment by burlexpo** [comment]
We seem to have _Django CMS History_ installed -- https://control.divio.com/control/126/edit/72911/apps/712/configure/ -- I just can't figure out how to access it.

**Comment by bethlakshmi** [comment]
I'm googling around and what I think I'm seeing is that Django CMS History is the undo/redo functionality that is exercised with the two circular arrow bars at the top of a page.  I fear that means that all it has a history of is the changes for that page.  And not the changes for pages underneath that page (like undeleting a child page).  But...a thing to try would be to go to the parent of the page you deleted and see if the undo/redo arrows are active there.

![Screen Shot 2020-01-07 at 8 19 37 PM](https://user-images.githubusercontent.com/4542707/71942423-289fd500-318b-11ea-8e72-2b652979593c.png)

**Comment by bethlakshmi** [comment]
I also asked our Divio folks to see if I'm wrong, as the docs are pretty sketchy.

**Comment by burlexpo** [comment]
There are the little circle arrows on the parent page, but they are greyed out.

**Comment by burlexpo** [comment]
Changed this to Low Priority and Enhancement.  Don't know if there's anything we can do about it.

**Comment by bethlakshmi** [comment]
I figured out that there ARE backups.  If this happens again, I think I can restore by putting one of the live backups up on test and then extracting the content you want.  HOWEVER, the backups are every 24 hours, so if you make a page and delete it an hour later, it's unlikely I can recover it.
