### ISSUE TITLE
Clean-up Vendor Display page

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#75]
1 - Create a "Featured" option when accepting vendors, similar to the Featured option for Act Bids.  

2 - Sort vendors alphabetically by name of business with the two sections (featured and non)

**Comment by bethlakshmi** [comment]
For Acts, I have two displays:
https://burlesque-expo.us.aldryn.io/scheduling/details/813

The special guests get a half-page spread.
The regular performers get a picture, and it only takes 1/4 of a page.

For Vendors right now - each one gets a 1/2 page spread.

Should I reduce the size of the not-featured vendors to a picture-only display the same way I do for regular performers?

Also - I got the part where you accept and set performers to featured - it's up on the test site:

https://burlesque-expo-stage.us.aldryn.io/vendor/review/1212

Is an example.

**Comment by bethlakshmi** [comment]
OK, changed the layout like we spoke about, it's up on the test server:

https://burlesque-expo-stage.us.aldryn.io/fashion_faire/

Set some vendors to "featured" to show the difference.  
At large/extra-large - it's 2 per row (featured), 3 for non-featured.
At medium (like a tablet) - it's 1 per row/2 per row
And at small everyone is the same size, because it's pretty small at that point.

**Comment by bethlakshmi** [comment]
DEPLOYED!
https://burlesque-expo.us.aldryn.io/fashion_faire/

All vendors are now "normal", go to vendor review to make any of them featured.
