### ISSUE TITLE
Make "Non-compete" a display section

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#88]
Currently, when I accept an act for a show, I can tag it with one of several categories -- normal act, hosted by, featuring, etc.  One of those is "non compete", which doesn't actually do anything.  I'd like to break the non-competitors out from the regular acts on the Main Event.  They can be the same size as regular acts, just in their own labeled section.

**Comment by bethlakshmi** [comment]
Having just refactored acts, I have a lot of context in my head for handling this.  May as well use it. :)

**Comment by bethlakshmi** [comment]
I've got a first implementation up on test:

https://burlesque-expo-stage.us.aldryn.io/scheduling/details/971/

The way it works:
- from here on out (nothing is grandfathered in) - if you set a not-special casting on an act, then the performer bio appears in a block with all the other acts of that sort.  The header of the block is whatever the category was called  - ie "Regular Act" or "Non-Compete"
- acts that were booked prior to this update will NOT have any casting, for anything that wasn't special, I gave it no special 'role' so they are all the same... as such they all appear in an extra block with the header "Check out these amazing performers".

The ActCastingOption in the admin will let you change the options, and the headers.  HOWEVER - once an act has been cast a certain way, this setting won't change it.  Ie, if you have Suzie the Shimmy booked as a "Regular Act", and then you decide to change "Regular Act" to "Amazing Acts" - then Suzie the Shimmy will still be in a block with the header "Regular Act" - until you recast her.


Questions:

- Should there be a difference between the Header on the show bio display and the setting on the act review form?  For example, should it be "Regular Act" on the form, and "Check out these Acts!" on the Show display page?  Can do.  It's more work, but medium-small (day or two).  This would be a good trick to also fix the fact that previously set acts are using the old role names.  
- How should the blocks be ordered on the event page?  It turns out, setting them up alphabetically is rather annoying.  So I'm willing to do what ever ordering makes sense to you...
- Do you want me to set previously-booked acts to anything?  That would not be hard.

**Comment by bethlakshmi** [comment]
Stopping here until we get a change to talk.  No rush.

**Comment by bethlakshmi** [comment]
My bad - won't have the branch with the update back until tomorrow morning... pushing through some dumb package updates that I have to push to test...

**Comment by bethlakshmi** [comment]
done!  Test server ready for you to play w.

**Comment by bethlakshmi** [comment]
Yeah, we need a "header" value for each casting type.  And grandfather in anyone pre-feature w. no casting value as a "Regular Act".  And give Regular act the header we were using "Check out these...."

**Comment by bethlakshmi** [comment]
deploying on production now

**Comment by bethlakshmi** [comment]
Done with GBE-88 pull request
