### ISSUE TITLE
Fixing Act Tech (thoughts)

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#91]
The Act Tech form that performers fill out is a nightmare and no one wants to deal with it.  Here are some suggestions for improved functionality.  The tricky part is we have about a month to get this tackled:

1. Allow performers to save their tech form as a draft (like the act bid).  Saving as a draft would *not* remove the alerts telling people they need to fill out their tech form.
2. Break the current Tech form into four parts: 
        1) Rehearsal Slot sign up (this doesn't need a draft state); 
        2) Audio information and music upload; 
        3) Lighting info; 
        4) Staging info (props, set pieces, Kitten interaction, etc.).  Potentially this could be tied to the rehearsal slot since it's info that every performer should know already
3. Each of the forms (except the staging one) probably have a "Basic Info" section and an "Advanced" section, which is collapsed but can be expanded.
        1. For *Lighting*, _Basic_ might be: the primary and secondary colors of your costume; the mood of your piece; do you want a follow spot; do you want a blackout at the end? I think there could also just be a "Let the tech team design it for me" option  _Advanced_ would be: specific cues at specific times; what color is the follow spot; starting position (wings; on stage; in the audience).
       2. For *Audio*, _Basic_ is uploading your music, the name of the song, and "Your music will start when the host finished your introduction.  If you want something other than that, please fill out that option below"; _Advanced_ is alternative starting cue; microphone information, which includes a space to specify if they want a handheld or headset microphone; whether they are bringing their own microphone or if we're providing it; and if they are bringing it, what is the make and model.  Mike Bergman is usually pretty responsive, so if you wanted, we could check in with him for input.

**Comment by bethlakshmi** [comment]
OK, I'm not 100% sure this is exactly your recommedation but I tried to live up to the spirit of it:

https://burlesque-expo-stage.us.aldryn.io/acttechinfo/wizard/1218

This is the wizard info for "Puttin on the Tease" - which I hope you can also see because you are tech crew.

Is what would be the "first" form - ie, rehearsal info + stuff that should be easy to answer up front, most of which is stage kitten info.   I think I got ALL the stage kitten info.  I also included some of what was "lighting info", because it gives some up front material that they shouldn't need to change.

I intend to follow up with more forms:
- lighting details 
- audio details

NOTE - this form is TOTALLY mocked.  It really does nothing yet.

**Comment by burlexpo** [comment]
OK -- thoughts These are all open-ended text boxes.  Performers will just drown.  Let's go with something like the attached.
[Basic Act Info.pdf](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/files/4240608/Basic.Act.Info.pdf)

**Comment by bethlakshmi** [comment]
**Questions:**  

- **Length of Track** - what is the use of this field?  In all these years, I've never seen anyone check the length of my track against the length of my act, and I've seen plenty of performers get confused by the two values.   I'd love to eliminate this one.  But if we must keep it, is it OK to auto-populate BOTH fields with the "length of act" value that we asked for in the act bid?  That's the most likely case.

- **Staging Info** - can we eliminate "I have no props or set pieces" - and assume that if they don't check any of the others, that's what they mean?  Easier for the user with a simple act.  And I was doing a check to make sure that they either did "nothing to set" or some combination of the others, and I've seen myself and many others fail at getting this right.

- Primary/Secondary colors - pull downs or text boxes?  I'm tempted toward pull downs of maybe 10 colors so the crew doesn't need to parse "Coquelicot", "Smaragdine", etc.  I would be willing to include "Rainbow", or "mix of Pastels", but basically do the typical 6, + white, black, brown, gold, silver, copper.

**Comment by bethlakshmi** [comment]
- follow spot - Yes/No
- Starting position - onstage, in the wings, in the house

**Comment by bethlakshmi** [comment]
OK, update is posted:
https://burlesque-expo-stage.us.aldryn.io/acttechinfo/wizard/1218

I think I got all the parts of your example, except:
- didn't include track length
- Song & Artist are NOT required - rationale is, if people do spoken word, they won't have one.

**Comment by bethlakshmi** [comment]
What is the deal here with draft?

Is is that for this form there are 2 options:
- Book rehearsal & save as draft = allow missing-but-required elements to be saved, so long as the rehearsal can be booked.
- Finalize = give errors if form is not complete.

Or something else?

**Comment by burlexpo** [comment]
Is there a reason why there are default values for "Pronoun"? 

- If you want to include options, it should be She/Her, He/Him, They/Them
- You've got it currently as "He/Hims"

**Comment by burlexpo** [comment]
**Drafts**
No Draft save on the basic info.  Everyone should know the answers to those questions.
Draft only on the Advance forms -- Lighting and Sound.

**Comment by bethlakshmi** [comment]
Making good progress on phase 1 (basic info & rehearsal setting)

- wizard step 1 actually works (the stuff we've been looking at in this thread)
- there's feedback on par with the rest of the modern site stuff (confirmation after form submit that rehearsal is booked, and tech info is saved).  Also there are error messages.  This is a pretty durable thread - I don't see users hitting errors unless they hit something I didn't see.  But there are some good errors for cases that could still conceivably happen.
- updated all links that pointed to the old edit to point to the new edit.

Stuff to do:

- run so many tests and make sure they work.
- update the make act info (create/edit act bid) - it used information that was stored the old way - it needs to store info the new way, or keeping the data in sync will be a pain
- redefine what "complete" means so that completing all fields on the new wizard step 1 = complete
- finish test design for wizard - hopefully I can base it off what we had, and update the tests.
- delete the old storage methods - keeping two just makes for chaos
- delete unused rehearsal booking code.

... not sure what else is left....

Later (not necessarily on this ticket) 

- I want to update booking acts into shows using some new (cleaner) function calls - I'm trying to clean up the connection between bidding and scheduling, and this is just a good step in the right direction.
- consider the idea of letting the user know if they book a conflict for themselves or a member of the group.  We do it other places, so it raises the expectation.  I figure this can wait until later, just jotting it down.  (I know where I'd put it - set_act, and allocate_act)

**Comment by bethlakshmi** [comment]
Tah Dah!
https://burlesque-expo-stage.us.aldryn.io/acttechinfo/wizard/1295

Now I need to do the tests, but until I find some bugs, this is what I plan to deploy...
