### ISSUE TITLE
Act Tech - Advanced Edition

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#94]
OK, I'm running my last test and have a Pull request waiting for me.

What is "advanced" act tech?

Proposal:
- do away completely with "Cue Info".  Backup plan - radically change it.
- keep audio stuff
- put it all into an "Advanced" section which is 100% optional.

Details:
- The "Advanced (optional)" section is in a panel below "Provide Technical Information".  It's a separate form, and has it's own buttons (just like Provide Technical Information)
- Audio information included:
   - bringing own mic (checkbox)
   - need a mic (checkbox)
- lighting information included:
   - background light color - small text box
   - overhead light color  - small text box
   - follow spot color  - small text box

BIG QUESTION - do we even want lighting color selections?  These are the ones that are most theater-specific, and thus the most difficult to program and have be accurate.  I suggest NOT drop boxes as drop boxes suggest that the option will definitely be available.  Having free form text lets us make a best effort and always adjust year to year.

Also - I'm willing to do "complicated cues" - if you want me to.  It would be:
 - an optional list, not more than 3 options
 - 2 fields, both are required: 
     - when it happens
     - what happens

Both as free form text.  

Doing these cues is easily 1/2 the work, or more, as the relationship of many-to-one (as opposed to "you get 1 cue, live with it") - is real work.  0 or 1 extra cue is a LOT easier.

When this is done, my plan is to DELETE extra data from the previous years as I don't see how the old format is useful to keep around.

**Comment by burlexpo** [comment]
We have LED lighting, so can provide almost any color.

Do whatever is easiest for you.

**Comment by bethlakshmi** [comment]
OK.  I'm killing cues.  I'll put in 1 box that is:

- if you need any special lighting change during your act, please describe it here:

And a box.  Which is optional.

Finished review on the basic stuff, and have it ready to install.  The data conversion needs a little hand-migration on one of the fields that people may have already filled out, so I will do the install when I know I have an hour or so (maybe on the T).

May start on this tonight or Saturday, incident willing.

**Comment by bethlakshmi** [comment]
Ta dah!
https://burlesque-expo-stage.us.aldryn.io/acttechinfo/wizard/1295

It doesn't work yet, but I think this is what we talked about last night.  Let me know ASAP if it's not right.

**Comment by burlexpo** [comment]
- Instead of "I own a mic" how about "I'm bringing a mic" or "I'll provide my mic"
- There's no info rollover on _Special Lighting Cues_.  We wrote it last night.
- For audio, we wanted something for a delayed music start, with the default being, "the music starts after the MC says your name at the end of your intro" but giving people (like Pru) the option to explain something different.  That could just be a text box which says something like "The default is your music will start playing after the MC finishes your introduction, regardless of where you are on stage or in the theatre.  If, instead, you want your music to start off of a cue, please tell us what that cue is".
